// Spanish box names (decision [196a9e] rule 2: short labels that frame the game get Spanish in the
// pack). Sent in the view as `nameEs` rather than bundled with the phone's strings (phone budget).
// The flavour lines are open-ended content and stay English under an "en inglés" marker.
export const ES_BOXES: Record<string, string> = {
  "Pirate's Chest": 'Cofre pirata',
  "Grandma's Suitcase": 'Maleta de la abuela',
  'Mystery Box': 'Caja misteriosa',
  'Lost Luggage': 'Equipaje perdido',
  'Cursed Doll': 'Muñeca maldita',
  'Old Piggy Bank': 'Alcancía vieja',
  'Treasure Map': 'Mapa del tesoro',
  'Tackle Box': 'Caja de pesca',
  'Antique Clock': 'Reloj antiguo',
  'Locked Safe': 'Caja fuerte cerrada',
  'Golden Egg': 'Huevo de oro',
  'Yard Sale Bin': 'Caja de venta de garaje',
  "Magician's Hat": 'Sombrero de mago',
  'Dragon Egg': 'Huevo de dragón',
  'Time Capsule': 'Cápsula del tiempo',
  'Sunken Crate': 'Caja hundida',
  "Wizard's Trunk": 'Baúl del hechicero',
  'Hot Potato': 'Papa caliente',
  'Crystal Ball': 'Bola de cristal',
  'Space Rock': 'Roca espacial',
  'Birthday Cake': 'Pastel de cumpleaños',
  'Vending Machine': 'Máquina expendedora',
  'Haunted Mirror': 'Espejo embrujado',
  'Lucky Clover': 'Trébol de la suerte',
  'Rusty Toolbox': 'Caja de herramientas oxidada',
  'Plain Envelope': 'Sobre sencillo',
  'Genie Lamp': 'Lámpara del genio',
  "Knight's Armor": 'Armadura de caballero',
  Pinata: 'Piñata',
  'Ice Chest': 'Hielera',
  'Snow Globe': 'Bola de nieve',
  'Jewelry Box': 'Joyero',
  'Bottle Message': 'Mensaje en una botella',
  'Robot Butler': 'Mayordomo robot',
  'Circus Cannon': 'Cañón de circo',
  'Secret Recipe': 'Receta secreta',
  'Carnival Prize': 'Premio de feria',
  'Golden Ticket': 'Boleto dorado',
  'Gumball Machine': 'Máquina de chicles',
  "Mummy's Tomb": 'Tumba de la momia',
  'Bank Vault': 'Bóveda del banco',
  'Raffle Drum': 'Tómbola',
  'Science Kit': 'Kit de ciencias',
  'Chocolate Box': 'Caja de chocolates',
  'Pawn Shop Guitar': 'Guitarra de casa de empeño',
  'Ghost Ship': 'Barco fantasma',
  'Moon Cheese': 'Queso lunar',
  'Volcano Rock': 'Roca volcánica',
  'Carpet Bag': 'Bolso de alfombra',
  'Old Radio': 'Radio viejo',
  'Casino Chip': 'Ficha de casino',
  'Scratch Card': 'Raspadito',
  'Crown Jewel': 'Joya de la corona',
  'Camping Chest': 'Baúl de campamento',
  'Hollow Book': 'Libro hueco',
  'Snake Oil': 'Remedio milagroso',
  'Parrot Cage': 'Jaula del loro',
  'Tiny Goblin': 'Duende diminuto',
  'Mail-Order Kit': 'Kit por catálogo',
  'Rocket Crate': 'Caja de cohetes',
  'Getaway Van': 'Camioneta de escape',
  'Swap Shop Box': 'Caja de trueque',
  'Cat Burglar Kit': 'Kit de ladrón de guante blanco',
  'Raccoon Family': 'Familia de mapaches',
  "Pickpocket's Coat": 'Abrigo del carterista',
  'Mystery Portal': 'Portal misterioso',
  'Bandit Mask': 'Antifaz de bandido',
  'Booby Trap': 'Trampa explosiva',
  'Identity Machine': 'Máquina de identidades',
  'Heist Plans': 'Planos del atraco',
  'Mutiny Barrel': 'Barril del motín',
  'Swap Potion': 'Poción de intercambio',
  'Quicksand Box': 'Caja de arenas movedizas',
  'Treasure Thief': 'Ladrón de tesoros',
  'Wooden Horse': 'Caballo de madera',
  'Wheel of Fate': 'Rueda del destino',
  'Poison Apple': 'Manzana envenenada',
  'Midnight Train': 'Tren de medianoche',
  "Fool's Gold": 'Oro de tontos',
  'Magpie Nest': 'Nido de urraca',
  // grand
  'Dragon Hoard': 'Tesoro del dragón',
  'Lost City': 'Ciudad perdida',
  'Royal Diamond': 'Diamante real',
  'Sunken Galleon': 'Galeón hundido',
  'Golden Goose': 'Gallina de los huevos de oro',
  'Dream Mansion': 'Mansión de ensueño',
  'Lottery Jackpot': 'Premio mayor de la lotería',
  'Wishing Well': 'Pozo de los deseos',
  'Mega Mystery Box': 'Megacaja misteriosa',
  'Bank Heist': 'Asalto al banco',
  "Emperor's Tomb": 'Tumba del emperador',
  "Pirate King's Map": 'Mapa del rey pirata',
  // spicy
  "Ex's Shoebox": 'Caja de zapatos de tu ex',
  'Bachelor Party Bag': 'Bolsa de la despedida de soltero',
  'Hotel Minibar': 'Minibar del hotel',
  'Divorce Papers': 'Papeles del divorcio',
  'Mystery Tattoo': 'Tatuaje misterioso',
  'Wedding Dress': 'Vestido de novia',
  'Office Party Photos': 'Fotos de la fiesta de la oficina',
  'Hangover Kit': 'Kit para la cruda',
  'Love Letters': 'Cartas de amor',
  'Casino Comps': 'Cortesías del casino',
  "Sugar Daddy's Card": 'Tarjeta del sugar daddy',
  'Vegas Chapel Deal': 'Boda exprés en Las Vegas',
  'Open Bar Tab': 'Cuenta de barra libre',
  'Stolen Diary': 'Diario robado',
  'Prenup Papers': 'Acuerdo prenupcial',
  'Walk of Shame Bag': 'Bolsa de la mañana siguiente',
  'Dating App Match': 'Match de la app de citas',
  'Mob Boss Suitcase': 'Maletín del capo',
  'Secret Drawer': 'Cajón secreto',
  'Midlife Crisis Car': 'Auto de la crisis de los cuarenta',
};
