// Spanish for Blind Auction's TV and phone screens, keyed by the English sentence (ADR-044).
// Content (lot names and flavour lines) stays in the deck's language.
export const ES_SCREENS: Record<string, string> = {
  // intro / how to play
  'Blind Auction': 'Subasta a Ciegas',
  'A mystery lot comes up, with a hint of what might be inside.':
    'Sale un lote misterioso, con una pista de lo que podría tener dentro.',
  'Bid in secret. The highest bid wins the lot and pays for it.':
    'Puja en secreto. La oferta más alta gana el lote y lo paga.',
  'Bid out loud from your phone: going once, going twice…':
    'Puja en voz alta desde tu teléfono: a la una, a las dos…',
  'The lot flips: treasure, trap, heist or swap. Most coins at the end wins.':
    'El lote se revela: tesoro, trampa, atraco o intercambio. Gana quien tenga más monedas al final.',
  'Everyone starts with {coin} {n}': 'Todos empiezan con {coin} {n}',
  'Live bidding needs everyone in one room, so tonight the bids are sealed.':
    'Las pujas en vivo necesitan a todos en la misma sala, así que hoy las ofertas son secretas.',
  // the lot
  'Lot {n} of {total}': 'Lote {n} de {total}',
  'THE GRAND LOT': 'EL GRAN LOTE',
  LIVE: 'EN VIVO',
  'What might be inside': 'Lo que podría haber dentro',
  LIKELY: 'PROBABLE',
  MAYBE: 'QUIZÁ',
  RARE: 'RARO',
  'Heist {n}%': 'Atraco {n}%',
  Swap: 'Intercambio',
  Double: 'Doble',
  Refund: 'Reembolso',
  Dud: 'Nada',
  'Secret bidding opens in a moment…': 'Las pujas secretas empiezan en un momento…',
  'Live bidding opens in a moment…': 'Las pujas en vivo empiezan en un momento…',
  'You have {n} coins': 'Tienes {n} monedas',
  // sealed bidding
  'Place your secret bids!': '¡Hagan sus ofertas secretas!',
  '{n} of {total} bids in': '{n} de {total} ofertas',
  'Bids are in secret': 'Las ofertas son secretas',
  'You only have {coin} {n}': 'Solo tienes {coin} {n}',
  // live bidding
  'Going once…': 'A la una…',
  'Going twice…': 'A las dos…',
  '{name} bids!': '¡{name} puja!',
  'Opening bid {coin} {n}. Who will start?': 'Oferta inicial {coin} {n}. ¿Quién empieza?',
  'Current bid': 'Oferta actual',
  'No bids yet': 'Aún no hay ofertas',
  'Bid {n}': 'Ofertar {n}',
  'All in': 'Todo',
  'Not enough coins': 'No te alcanza',
  "You're winning! 🔨": '¡Vas ganando! 🔨',
  'Outbid! Try again.': '¡Te superaron! Inténtalo otra vez.',
  "You're already winning": 'Ya vas ganando',
  'Live bidding — watch the TV': 'Pujas en vivo: mira la TV',
  // sold
  'Bidding is closed.': 'Las pujas están cerradas.',
  'Going… going… gone!': 'A la una… a las dos… ¡adjudicado!',
  '{name} paid {coin} {n} for it…': '{name} pagó {coin} {n} por esto…',
  'Nobody bid on it. What did the room miss?': 'Nadie pujó. ¿Qué se perdieron?',
  'No takers!': '¡Nadie lo quiso!',
  SOLD: 'VENDIDO',
  'NO TAKERS': 'SIN OFERTAS',
  'SOLD to {name} for {coin} {n}!': '¡VENDIDO a {name} por {coin} {n}!',
  'Tie: fewer coins wins': 'Empate: gana quien tiene menos monedas',
  '{n} passed': '{n} pasaron',
  '{n} lower bids': '{n} ofertas más bajas',
  // flip
  JACKPOT: 'PREMIO',
  DOUBLE: 'DOBLE',
  TRAP: 'TRAMPA',
  HEIST: 'ATRACO',
  SWAP: 'INTERCAMBIO',
  REFUND: 'REEMBOLSO',
  DUD: 'NADA',
  UNSOLD: 'SIN VENDER',
  '+{n}!': '¡+{n}!',
  'DOUBLE! +{n}': '¡DOBLE! +{n}',
  'TRAP! −{n}': '¡TRAMPA! −{n}',
  'TRAP! Nothing left to lose': '¡TRAMPA! No quedaba nada que perder',
  'HEIST! {a} steals {n} from {b}': '¡ATRACO! {a} le roba {n} a {b}',
  'HEIST! Nothing to steal!': '¡ATRACO! ¡No había nada que robar!',
  'SWAP! {a} ⇄ {b}': '¡INTERCAMBIO! {a} ⇄ {b}',
  'Money back: +{n}': 'Te devuelven: +{n}',
  'A dud.': 'Nada de nada.',
  'Nobody bought it.': 'Nadie lo compró.',
  'It was: {what}': 'Era: {what}',
  // own lines
  '👀 Watch the TV': '👀 Mira la TV',
  'Who bid the most?': '¿Quién ofreció más?',
  'What was inside?': '¿Qué había dentro?',
  'You won it for {coin} {n}!': '¡Lo ganaste por {coin} {n}!',
  'Outbid by {name}': 'Te superó {name}',
  '{name} won it for {coin} {n}': '{name} lo ganó por {coin} {n}',
  '{name} stole {n} from you': '{name} te robó {n}',
  '{name} swapped coins with you': '{name} intercambió monedas contigo',
  '+{n} coins!': '¡+{n} monedas!',
  'A trap! −{n} coins': '¡Una trampa! −{n} monedas',
  'A trap! Nothing left to lose': '¡Una trampa! No quedaba nada que perder',
  'You stole {n} from {name}!': '¡Le robaste {n} a {name}!',
  'Nothing to steal!': '¡No había nada que robar!',
  'You swapped with {name}': 'Intercambiaste con {name}',
  'A dud. Nothing inside.': 'Nada. Estaba vacío.',
  'a trap (−{n})': 'una trampa (−{n})',
  'a heist (+{n})': 'un atraco (+{n})',
  'a swap': 'un intercambio',
  'money back': 'reembolso',
  'a dud': 'nada',
  // waiting
  'One moment…': 'Un momento…',
  'Look at the TV': 'Mira la TV',
  "That's the auction!": '¡Y así termina la subasta!',
};
