// Spanish for Mystery Box's TV and phone screens, keyed by the English sentence (ADR-044).
// Content (box names and flavour lines) stays in the deck's language.
export const ES_SCREENS: Record<string, string> = {
  // the rules
  'A mystery box shows what might be inside, and the odds.':
    'Una caja misteriosa muestra lo que podría tener dentro, y sus probabilidades.',
  'Bet your coins in secret on what you think is inside. Long shots pay big.':
    'Apuesta tus monedas en secreto a lo que crees que hay dentro. Lo improbable paga mucho.',
  'The box opens: call it right and you get paid by the odds. Most coins at the end wins.':
    'La caja se abre: si aciertas, cobras según las probabilidades. Gana quien tenga más monedas al final.',
  'Everyone starts with {coin} {n}': 'Todos empiezan con {coin} {n}',
  'Tap Ready on your phone · {n} of {total} ready':
    'Toca «Listo» en tu teléfono · {n} de {total} listos',
  "I'm ready": 'Estoy listo',
  '✓ Ready': '✓ Listo',
  '✓ Ready · waiting for {n} more': '✓ Listo · faltan {n}',
  'Here comes the first box…': 'Ahí viene la primera caja…',
  // the box
  'Box {n} of {total}': 'Caja {n} de {total}',
  'Box {n}/{total}': 'Caja {n}/{total}',
  'THE GRAND BOX · PAYS DOUBLE': 'LA GRAN CAJA · PAGA DOBLE',
  'Grand box ×2': 'Gran caja ×2',
  "What's inside?": '¿Qué hay dentro?',
  'What is inside?': '¿Qué hay dentro?',
  'Betting opens in a moment: what is inside?':
    'Las apuestas abren en un momento: ¿qué hay dentro?',
  LIKELY: 'PROBABLE',
  MAYBE: 'QUIZÁ',
  RARE: 'RARO',
  'pays {x}': 'paga {x}',
  'You have {n} coins': 'Tienes {n} monedas',
  // what a box can hold
  Treasure: 'Tesoro',
  Jackpot: 'Premio gordo',
  'A trap': 'Una trampa',
  'A raccoon': 'Un mapache',
  'A magic mirror': 'Un espejo mágico',
  Twins: 'Gemelos',
  'A receipt': 'Un recibo',
  Nothing: 'Nada',
  // betting
  'Place your bets!': '¡Hagan sus apuestas!',
  '{n} of {total} bets in': '{n} de {total} apuestas',
  'Bets are secret': 'Las apuestas son secretas',
  'Pick what is inside': 'Elige qué hay dentro',
  'Pick what is inside first': 'Primero elige qué hay dentro',
  'Choose your stake': 'Elige tu apuesta',
  'Bet {coin} {n} on {what}': 'Apostar {coin} {n} a {what}',
  'Change to {coin} {n} on {what}': 'Cambiar a {coin} {n} a {what}',
  '✓ {coin} {n} on {what}': '✓ {coin} {n} a {what}',
  'Sit this one out': 'Paso esta ronda',
  '✓ Sitting this one out': '✓ Pasas esta ronda',
  'You only have {coin} {n}': 'Solo tienes {coin} {n}',
  'You ran out of coins: here are {coin} {n} to play with':
    'Te quedaste sin monedas: aquí tienes {coin} {n} para jugar',
  // the open
  'Bets are closed. What’s inside?': 'Apuestas cerradas. ¿Qué hay dentro?',
  'Nobody bet. What’s inside?': 'Nadie apostó. ¿Qué hay dentro?',
  "It's {what}!": '¡Es {what}!',
  'INSIDE!': '¡DENTRO!',
  'Nobody called it!': '¡Nadie acertó!',
  '{n} lost their stake': '{n} perdieron su apuesta',
  // own lines
  '👀 Watch the TV': '👀 Mira la TV',
  'You called it! +{n}': '¡Acertaste! +{n}',
  'It was {what}. Your {bet} paid {back}.': 'Era {what}. Tus {bet} pagaron {back}.',
  'Not this time: −{n}': 'Esta vez no: −{n}',
  'It was {what}.': 'Era {what}.',
  'You sat this one out': 'Pasaste esta ronda',
  // waiting
  'One moment…': 'Un momento…',
  'Look at the TV': 'Mira la TV',
  "That's the last box!": '¡Esa fue la última caja!',
  'Tap a card, then choose your coins': 'Toca una carta y luego elige tus monedas',
  // live events
  Twist: 'Giro',
  '⏰ Early bird: bet now for up to ×1.25 more — it slides to ×1.00 at the buzzer.':
    '⏰ Madrugador: apuesta ya y gana hasta ×1.25 más; baja a ×1.00 al sonar el timbre.',
  "🛟 Insurance: pay 10 % more to get half your stake back if you're wrong.":
    '🛟 Seguro: paga un 10 % más y recupera la mitad de tu apuesta si fallas.',
  '🧮 The crowd sets the odds: right calls split the whole pot — back the unpopular pick!':
    '🧮 El público fija las cuotas: los aciertos se reparten todo el bote. ¡Apuesta por lo impopular!',
  '🛟 Insured (+{coin} {n})': '🛟 Asegurado (+{coin} {n})',
  '🛟 Add insurance': '🛟 Añadir seguro',
  '👁 Peek: pay to rule out one wrong answer, on your phone only.':
    '👁 Espiar: paga para descartar una respuesta equivocada, solo en tu celular.',
  '👁 Ruled out: the struck card': '👁 Descartada: la carta tachada',
  '👁 Peek: rule one out ({coin} {n})': '👁 Espiar: descarta una ({coin} {n})',
  'A goat behind door {n}! You are switching to door {m}.':
    '¡Una cabra tras la puerta {n}! Vas a cambiar a la puerta {m}.',
  Blackjack: 'Blackjack',
  'Beat the dealer without going over 21. Win ×2, blackjack ×2.5.':
    'Gánale a la banca sin pasarte de 21. Ganas ×2, blackjack ×2.5.',
  'Your hand': 'Tu mano',
  Dealer: 'Banca',
  Bust: 'Te pasaste',
  'No stake on this hand: watch the table.': 'Sin apuesta en esta mano: mira la mesa.',
  HIT: 'PEDIR',
  STAND: 'PLANTARSE',
  'Dealer shows': 'La banca muestra',
  'Bust! {n}': '¡Te pasaste! {n}',
  '21!': '¡21!',
  'You have {n}': 'Tienes {n}',
  'Standing. The dealer plays when everyone is done.':
    'Te plantaste. La banca juega cuando todos terminen.',
  'Hit for another card, or stand.': 'Pide otra carta o plántate.',
  'The dealer plays…': 'Juega la banca…',
  'Hit or stand on your phone!': '¡Pidan o plántense en el teléfono!',
  'Beat the dealer without going over 21. Win ×2, blackjack ×2.5, a tie gives the stake back.':
    'Gánenle a la banca sin pasarse de 21. Ganan ×2, blackjack ×2.5; el empate devuelve lo apostado.',
  'Your stake came back. It was {what}.': 'Recuperaste lo apostado. Fue {what}.',
  'Your pull: {n}% of your team': 'Tu jalón: {n}% de tu equipo',
  'Ghost Hunt': 'Cazafantasmas',
  'A ghost hides in one of four rooms. Right room pays ×4.':
    'Un fantasma se esconde en uno de cuatro cuartos. El cuarto correcto paga ×4.',
  'Defuse the Bomb': 'Desactiva la bomba',
  'Four wires, one stops the bomb. Pick it: ×4.':
    'Cuatro cables, uno detiene la bomba. Adivínalo: ×4.',
  Bedroom: 'Recámara',
  Kitchen: 'Cocina',
  Bathroom: 'Baño',
  Attic: 'Ático',
  'Red wire': 'Cable rojo',
  'Blue wire': 'Cable azul',
  'Yellow wire': 'Cable amarillo',
  'Green wire': 'Cable verde',
  empty: 'vacío',
  cut: 'cortado',
  'BOO!': '¡BU!',
  'defused!': '¡desactivada!',
  'Bets are closed. Flashlights on!': 'Apuestas cerradas. ¡Linternas encendidas!',
  'Bets are closed. Snip… snip…': 'Apuestas cerradas. Clic… clic…',
  'Penalty Kick': 'Penal',
  'One shot, one keeper. Goal, save, or off the post?':
    'Un tiro, un portero. ¿Gol, atajada o al palo?',
  Goal: 'Gol',
  Saved: 'Atajada',
  'Off the post': 'Al palo',
  'GOAL!': '¡GOL!',
  'SAVED!': '¡ATAJADA!',
  'Off the post!': '¡Al palo!',
  'Bets are closed. Here comes the kick!': 'Apuestas cerradas. ¡Ahí va el tiro!',
  'Pick a card': 'Elige una carta',
  'Pick a player': 'Elige a alguien',
  'drawn {list}': 'salieron {list}',
  'Lucky Numbers': 'Números de la suerte',
  'Pick three numbers. Five balls drop. Match them all for ×30!':
    'Elige tres números. Caen cinco bolas. ¡Acierta los tres y gana ×30!',
  'Your numbers': 'Tus números',
  'No match: you lose it': 'Ningún acierto: lo pierdes',
  '1 match: stake back': '1 acierto: recuperas lo apostado',
  '2 matches: ×{x}': '2 aciertos: ×{x}',
  '3 matches: ×{x}': '3 aciertos: ×{x}',
  'Pick {n} lucky numbers': 'Elige {n} números de la suerte',
  'Your numbers: {list}': 'Tus números: {list}',
  'Your lucky numbers': 'Tus números de la suerte',
  'Bets are closed. Here come the balls!': 'Apuestas cerradas. ¡Ahí vienen las bolas!',
  'Pick your three numbers first': 'Primero elige tus tres números',
  'Coin Streak': 'Racha de monedas',
  'Heads, heads, heads… how long before tails?': 'Cara, cara, cara… ¿cuánto hasta que salga cruz?',
  'Tails first': 'Cruz a la primera',
  '1 or 2 heads': '1 o 2 caras',
  '3+ heads': '3 o más caras',
  'Tails! A streak of {n}': '¡Cruz! Una racha de {n}',
  '{n} heads in a row!': '¡{n} caras seguidas!',
  'Heads! {n} so far…': '¡Cara! Van {n}…',
  'Bets are closed. Flip it!': 'Apuestas cerradas. ¡A lanzar!',
  'splits the pot': 'se reparte el bote',
  'Shell Game': 'Los vasitos',
  'Stake the pot, follow the ball. The bigger the pot, the faster the cups.':
    'Apuesta al bote y sigue la bolita. Cuanto más grande el bote, más rápidos los vasos.',
  'Cup 1': 'Vaso 1',
  'Cup 2': 'Vaso 2',
  'Cup 3': 'Vaso 3',
  'Cup {n}': 'Vaso {n}',
  'Nice and slow. Keep your eyes on the ball.': 'Despacito. No le quiten el ojo a la bolita.',
  'A warm-up. Easy money.': 'Calentamiento. Dinero fácil.',
  'Double speed! Still with me?': '¡Doble velocidad! ¿Siguen conmigo?',
  '×2. Blink and you miss it.': '×2. Parpadean y se lo pierden.',
  'Triple speed! Eyes up!': '¡Triple velocidad! ¡Ojos arriba!',
  '×3. The cups are getting ideas.': '×3. Los vasos se están animando.',
  'FIVE times! Is that the ball or a rumour?': '¡CINCO veces! ¿Eso es la bolita o un rumor?',
  '×5. Your eyes are lying to you.': '×5. Sus ojos les están mintiendo.',
  'EIGHT times! Nobody can follow this!': '¡OCHO veces! ¡Nadie puede seguir esto!',
  '×8. Pure chaos. Good luck.': '×8. Caos puro. Buena suerte.',
  'TEN TIMES! The cups have left the building!': '¡DIEZ VECES! ¡Los vasos se fueron del edificio!',
  '×10. Just guess. Seriously.': '×10. Adivinen. En serio.',
  '👀 Watch the ball on the TV!': '👀 ¡Sigan la bolita en la TV!',
  'Follow the ball!': '¡Sigue la bolita!',
  'Which cup?': '¿Qué vaso?',
  'No coins in the pot: watch the others pick.':
    'Sin monedas en el bote: mira cómo eligen los demás.',
  'Which cup hides the ball?': '¿Qué vaso esconde la bolita?',
  'Your {coin} {n} is in the pot': 'Tus {coin} {n} están en el bote',
  'Watch the ball!': '¡Sigan la bolita!',
  'The pot: {coin} {n}': 'El bote: {coin} {n}',
  '×{n} speed': 'velocidad ×{n}',
  'Which cup? Pick on your phone!': '¿Qué vaso? ¡Elijan en el teléfono!',
  'Right calls split the whole pot by their stakes. All right or all wrong: stakes back.':
    'Los aciertos se reparten todo el bote según lo apostado. Todos aciertan o todos fallan: se devuelve lo apostado.',
  'Cups up! Where is the ball?': '¡Arriba los vasos! ¿Dónde está la bolita?',
  'Put coins in the pot. You pick a cup after the shuffle; the bigger the pot, the faster it goes!':
    'Pon monedas en el bote. Eliges vaso después de la mezcla; ¡cuanto más grande el bote, más rápido va!',
  'Put {coin} {n} in the pot': 'Poner {coin} {n} en el bote',
  'Stake back: {coin} {n}': 'Te devuelven {coin} {n}',
  'Everyone called it the same way. It was {what}.': 'Todos dijeron lo mismo. Era {what}.',
  'Tug of War': 'Jalar la cuerda',
  'Two teams, one rope. Bet on your side, then tap to pull!':
    'Dos equipos, una cuerda. Apuesta por tu lado y luego toca para jalar.',
  Sun: 'Sol',
  Moon: 'Luna',
  'Team Sun': 'Equipo Sol',
  'Team Moon': 'Equipo Luna',
  'PULL!': '¡JALA!',
  'No stake on this one: your pulls count for nothing': 'Sin apuesta: tus jalones no cuentan',
  'Your pull is {n}% of your team’s': 'Tu jalón es el {n}% del de tu equipo',
  'PULL! Tap your phone as fast as you can!':
    '¡JALEN! ¡Toquen el teléfono lo más rápido que puedan!',
  'Every tap counts as much as your share of your team’s bet.':
    'Cada toque cuenta según tu parte de la apuesta de tu equipo.',
  'Dead heat! Every stake goes back.': '¡Empate! Se devuelven todas las apuestas.',
  'Time! Which side held on?': '¡Tiempo! ¿Qué lado aguantó?',
  // The game's name is a brand: it stays English on Spanish screens (#decisions, Part 00 a).
  'Mystery Box': 'Mystery Box',
  'No passes yet': 'Aún sin pases',
  '1 pass': '1 pase',
  'Everyone: {tier} · {n}% · pays {x}': 'Todos: {tier} · {n}% · paga {x}',
  You: 'Tú',
  'Pick who will be holding it': 'Elige quién la tendrá',
  'Pick who will be holding it first': 'Primero elige quién la tendrá',
  'Pick what will happen': 'Elige qué pasará',
  'You can’t bet on yourself: pick someone else': 'No puedes apostar por ti: elige a otra persona',
  'Hot Potato': 'Papa caliente',
  'Tap to pass it on. Who is holding it when it pops?':
    'Tócala para pasarla. ¿Quién la tiene cuando explota?',
  'Tap to pass!': '¡Toca para pasarla!',
  'You have the potato!': '¡Tienes la papa!',
  '{name} has the potato': '{name} tiene la papa',
  '{n} passes': '{n} pases',
  'Pass it on before it pops!': '¡Pásala antes de que explote!',
  'POP! {name} got burnt': '¡PUM! {name} se quemó',
  'Bets are closed. Pass the potato!': 'Apuestas cerradas. ¡Pasen la papa!',
  'Stay or switch?': '¿Te quedas o cambias?',
  'A goat behind door {n}! Keep your door, or switch to the other one.':
    '¡Una cabra tras la puerta {n}! Quédate con tu puerta o cambia a la otra.',
  '{n} of {total} have chosen': '{n} de {total} ya eligieron',
  'Doors are final. Where is the car?': 'Puertas decididas. ¿Dónde está el auto?',
  'Door {n}': 'Puerta {n}',
  'Door 1': 'Puerta 1',
  'Door 2': 'Puerta 2',
  'Door 3': 'Puerta 3',
  'Three Doors': 'Tres puertas',
  'A car behind one, goats behind two. Stay or switch?':
    'Un auto tras una, cabras tras dos. ¿Te quedas o cambias?',
  'No stake on these doors: watch the others choose.':
    'No apostaste en estas puertas: mira cómo eligen los demás.',
  'A goat behind your door {n}! Pick one of the other two.':
    '¡Una cabra tras tu puerta {n}! Elige una de las otras dos.',
  'A goat behind door {n}! You are on door {m}.':
    '¡Una cabra tras la puerta {n}! Estás en la puerta {m}.',
  'Stay on door {n}': 'Quedarme en la puerta {n}',
  'Switch to door {n}': 'Cambiar a la puerta {n}',
  'Choose before the doors open.': 'Elige antes de que se abran las puertas.',
  '✓ Locked in. You can still change.': '✓ Elegido. Aún puedes cambiar.',
  'Bets are closed. And they’re off!': 'Apuestas cerradas. ¡Arrancan!',
  'Bets are closed. Roll the dice!': 'Apuestas cerradas. ¡A tirar los dados!',
  'Bets are closed. Spin the wheel!': 'Apuestas cerradas. ¡A girar la ruleta!',
  'The race': 'La carrera',
  '{what} wins!': '¡Gana {what}!',
  'A winner': 'Un ganador',
  Turtle: 'Tortuga',
  Rabbit: 'Conejo',
  Duck: 'Pato',
  Snail: 'Caracol',
  Horse: 'Caballo',
  Pig: 'Cerdo',
  Flamingo: 'Flamenco',
  Squirrel: 'Ardilla',
  Hedgehog: 'Erizo',
  Rooster: 'Gallo',
  'Under 7': 'Menos de 7',
  'Lucky 7': '7 de la suerte',
  'Over 7': 'Más de 7',
  Gold: 'Oro',
  Diamond: 'Diamante',
  Crown: 'Corona',
  Pizza: 'Pizza',
  Rocket: 'Cohete',
  Guitar: 'Guitarra',
  Unicorn: 'Unicornio',
  Donut: 'Dona',
  Trophy: 'Trofeo',
  'Top hat': 'Sombrero de copa',
  Taco: 'Taco',
  Teddy: 'Osito',
  Clover: 'Trébol',
  Bell: 'Campana',
  Gift: 'Regalo',
  Star: 'Estrella',
  Octopus: 'Pulpo',
  Cherries: 'Cerezas',
  'Disco ball': 'Bola disco',
  Dino: 'Dino',
  'Animal Race': 'Carrera de animales',
  'Dice Roll': 'Tirada de dados',
  'Prize Wheel': 'Ruleta de premios',
  'Four racers, one finish line. Who wins?': 'Cuatro corredores, una meta. ¿Quién gana?',
  'Two dice. Under seven, lucky seven, or over?':
    'Dos dados. ¿Menos de siete, siete de la suerte o más?',
  'Round and round it goes. Where it stops…': 'Gira y gira. Dónde para…',
};
