// Spanish for Blind Auction's TV and phone screens, keyed by the English sentence (ADR-044).
// Content (box names and flavour lines) stays in the deck's language.
export const ES_SCREENS: Record<string, string> = {
  // the rules
  'Blind Auction': 'Subasta a Ciegas',
  'A mystery box shows what might be inside, and the odds.':
    'Una caja misteriosa muestra lo que podría tener dentro, y sus probabilidades.',
  'Bet your coins in secret on what you think is inside. Long shots pay big.':
    'Apuesta tus monedas en secreto a lo que crees que hay dentro. Lo improbable paga mucho.',
  'The box opens: call it right and you get paid by the odds. Most coins at the end wins.':
    'La caja se abre: si aciertas, cobras según las probabilidades. Gana quien tenga más monedas al final.',
  'Everyone starts with {coin} {n}': 'Todos empiezan con {coin} {n}',
  'Tap Ready on your phone · {n} of {total} ready':
    'Toca «Listo» en tu teléfono · {n} de {total} listos',
  "I'm ready": 'Estoy listo',
  '✓ Ready': '✓ Listo',
  '✓ Ready · waiting for {n} more': '✓ Listo · faltan {n}',
  'Here comes the first box…': 'Ahí viene la primera caja…',
  // the box
  'Box {n} of {total}': 'Caja {n} de {total}',
  'Box {n}/{total}': 'Caja {n}/{total}',
  'THE GRAND BOX · PAYS DOUBLE': 'LA GRAN CAJA · PAGA DOBLE',
  'Grand box ×2': 'Gran caja ×2',
  "What's inside?": '¿Qué hay dentro?',
  'What is inside?': '¿Qué hay dentro?',
  'Betting opens in a moment: what is inside?':
    'Las apuestas abren en un momento: ¿qué hay dentro?',
  LIKELY: 'PROBABLE',
  MAYBE: 'QUIZÁ',
  RARE: 'RARO',
  'pays {x}': 'paga {x}',
  'You have {n} coins': 'Tienes {n} monedas',
  // what a box can hold
  Treasure: 'Tesoro',
  Jackpot: 'Premio gordo',
  'A trap': 'Una trampa',
  'A raccoon': 'Un mapache',
  'A magic mirror': 'Un espejo mágico',
  Twins: 'Gemelos',
  'A receipt': 'Un recibo',
  Nothing: 'Nada',
  // betting
  'Place your bets!': '¡Hagan sus apuestas!',
  '{n} of {total} bets in': '{n} de {total} apuestas',
  'Bets are secret': 'Las apuestas son secretas',
  'Pick what is inside': 'Elige qué hay dentro',
  'Pick what is inside first': 'Primero elige qué hay dentro',
  'Choose your stake': 'Elige tu apuesta',
  'Bet {coin} {n} on {what}': 'Apostar {coin} {n} a {what}',
  'Change to {coin} {n} on {what}': 'Cambiar a {coin} {n} a {what}',
  '✓ {coin} {n} on {what}': '✓ {coin} {n} a {what}',
  'Sit this one out': 'Paso esta ronda',
  '✓ Sitting this one out': '✓ Pasas esta ronda',
  'You only have {coin} {n}': 'Solo tienes {coin} {n}',
  'You ran out of coins: here are {coin} {n} to play with':
    'Te quedaste sin monedas: aquí tienes {coin} {n} para jugar',
  // the open
  'Bets are closed. What’s inside?': 'Apuestas cerradas. ¿Qué hay dentro?',
  'Nobody bet. What’s inside?': 'Nadie apostó. ¿Qué hay dentro?',
  "It's {what}!": '¡Es {what}!',
  'INSIDE!': '¡DENTRO!',
  'Nobody called it!': '¡Nadie acertó!',
  '{n} lost their stake': '{n} perdieron su apuesta',
  // own lines
  '👀 Watch the TV': '👀 Mira la TV',
  'You called it! +{n}': '¡Acertaste! +{n}',
  'It was {what}. Your {coin} {bet} paid {coin} {back}.':
    'Era {what}. Tus {coin} {bet} pagaron {coin} {back}.',
  'Not this time: −{n}': 'Esta vez no: −{n}',
  'It was {what}.': 'Era {what}.',
  'You sat this one out': 'Pasaste esta ronda',
  // waiting
  'One moment…': 'Un momento…',
  'Look at the TV': 'Mira la TV',
  "That's the last box!": '¡Esa fue la última caja!',
  // live events
  'Stay or switch?': '¿Te quedas o cambias?',
  'A goat behind door {n}! Keep your door, or switch to the other one.':
    '¡Una cabra tras la puerta {n}! Quédate con tu puerta o cambia a la otra.',
  '{n} of {total} have chosen': '{n} de {total} ya eligieron',
  'Doors are final. Where is the car?': 'Puertas decididas. ¿Dónde está el coche?',
  'Door {n}': 'Puerta {n}',
  'Door 1': 'Puerta 1',
  'Door 2': 'Puerta 2',
  'Door 3': 'Puerta 3',
  'Three Doors': 'Tres puertas',
  'A car behind one, goats behind two. Stay or switch?':
    'Un coche tras una, cabras tras dos. ¿Te quedas o cambias?',
  'No stake on these doors: watch the others choose.':
    'No apostaste en estas puertas: mira cómo eligen los demás.',
  'A goat behind your door {n}! Pick one of the other two.':
    '¡Una cabra tras tu puerta {n}! Elige una de las otras dos.',
  'A goat behind door {n}! You are on door {m}.':
    '¡Una cabra tras la puerta {n}! Estás en la puerta {m}.',
  'Stay on door {n}': 'Quedarme en la puerta {n}',
  'Switch to door {n}': 'Cambiar a la puerta {n}',
  'Choose before the doors open.': 'Elige antes de que se abran las puertas.',
  '✓ Locked in. You can still change.': '✓ Elegido. Aún puedes cambiar.',
  'Bets are closed. And they’re off!': 'Apuestas cerradas. ¡Arrancan!',
  'Bets are closed. Roll the dice!': 'Apuestas cerradas. ¡A tirar los dados!',
  'Bets are closed. Spin the wheel!': 'Apuestas cerradas. ¡A girar la ruleta!',
  'The race': 'La carrera',
  '{what} wins!': '¡Gana {what}!',
  'A winner': 'Un ganador',
  Turtle: 'Tortuga',
  Rabbit: 'Conejo',
  Duck: 'Pato',
  Snail: 'Caracol',
  Horse: 'Caballo',
  Pig: 'Cerdo',
  Flamingo: 'Flamenco',
  Squirrel: 'Ardilla',
  Hedgehog: 'Erizo',
  Rooster: 'Gallo',
  'Under 7': 'Menos de 7',
  'Lucky 7': '7 de la suerte',
  'Over 7': 'Más de 7',
  Gold: 'Oro',
  Diamond: 'Diamante',
  Crown: 'Corona',
  Pizza: 'Pizza',
  Rocket: 'Cohete',
  Guitar: 'Guitarra',
  Unicorn: 'Unicornio',
  Donut: 'Dona',
  Trophy: 'Trofeo',
  'Top hat': 'Sombrero de copa',
  Taco: 'Taco',
  Teddy: 'Osito',
  Clover: 'Trébol',
  Bell: 'Campana',
  Gift: 'Regalo',
  Star: 'Estrella',
  Octopus: 'Pulpo',
  Cherries: 'Cerezas',
  'Disco ball': 'Bola disco',
  Dino: 'Dino',
  'Animal Race': 'Carrera de animales',
  'Dice Roll': 'Tirada de dados',
  'Prize Wheel': 'Ruleta de premios',
  'Four racers, one finish line. Who wins?': 'Cuatro corredores, una meta. ¿Quién gana?',
  'Two dice. Under seven, lucky seven, or over?':
    'Dos dados. ¿Menos de siete, siete de la suerte o más?',
  'Round and round it goes. Where it stops…': 'Gira y gira. Dónde para…',
};
