// Secret Hitler's words in Spanish, keyed by the English sentence (ADR-044). Screens write
// `L('…')` from `useT(STRINGS)`; the manifest's lines live in manifest.es.json (ADR-049), and
// scripts/i18n-coverage.test.ts fails until each has its Spanish. Ja and Nein stay as they are in
// both languages (SPEC §19). `{name}` marks a placeholder.
import type { Strings } from '@partybox/game-sdk/ui';

export const STRINGS: Strings = {
  es: {
    'Last call': 'Última llamada',
    'Start now': 'Empezar ya',
    'Based on Secret Hitler by Max Temkin, Mike Boxleiter & Tommy Maranges · CC BY-NC-SA 4.0':
      'Basado en Secret Hitler de Max Temkin, Mike Boxleiter y Tommy Maranges · CC BY-NC-SA 4.0',
    // server/scoring.ts — the results line (ADR-052)
    Liberals: 'Liberales',
    Fascists: 'Fascistas',
    'Five Liberal laws: the Liberals win!': 'Cinco leyes liberales: ¡ganan los Liberales!',
    'Hitler is dead: the Liberals win!': 'Hitler ha muerto: ¡ganan los Liberales!',
    'Hitler fled: the Liberals win!': 'Hitler huyó: ¡ganan los Liberales!',
    'Six Fascist laws: the Fascists win!': 'Seis leyes fascistas: ¡ganan los Fascistas!',
    'Hitler is Chancellor: the Fascists win!': 'Hitler es Canciller: ¡ganan los Fascistas!',
    'Too few left: the Liberals win!': 'Quedan muy pocos: ¡ganan los Liberales!',
    'Too few left: the Fascists win!': 'Quedan muy pocos: ¡ganan los Fascistas!',
    // seating: the rules, the ready-up and the 3 · 2 · 1 (the owner's pacing rule)
    'How to play': 'Cómo se juega',
    Briefing: 'Informe',
    'Secret roles': 'Roles secretos',
    'Everyone has a secret role. The Fascists know each other; the Liberals know no one.':
      'Todos tienen un rol secreto. Los Fascistas se conocen entre sí; los Liberales no conocen a nadie.',
    'Elect a government': 'Elijan un gobierno',
    'The President names a Chancellor and everyone votes Ja! or Nein! If it passes, the two secretly pass one law.':
      'El Presidente nombra a un Canciller y todos votan Ja! o Nein! Si se aprueba, los dos aprueban en secreto una ley.',
    'How to win': 'Cómo ganar',
    'Liberals: 5 Liberal laws, or execute Hitler. Fascists: 6 Fascist laws, or Hitler elected Chancellor after 3.':
      'Liberales: 5 leyes liberales, o ejecutar a Hitler. Fascistas: 6 leyes fascistas, o Hitler elegido Canciller después de 3.',
    '{ready} of {total} ready': '{ready} de {total} listos',
    'Read your dossier, then tap Got it': 'Lee tu expediente y luego toca Entendido',
    '✓ Ready': '✓ Listo',
    Voted: 'Votó',
    'Waiting for the others': 'Esperando a los demás',
    'The session opens': 'Se abre la sesión',
    // roles, parties, powers
    Liberal: 'Liberal',
    Fascist: 'Fascista',
    Hitler: 'Hitler',
    'Enact 5 Liberal policies, or execute Hitler.':
      'Aprueba 5 leyes liberales, o ejecuta a Hitler.',
    'Enact 6 Fascist policies, or be elected Chancellor after 3.':
      'Aprueba 6 leyes fascistas, o sé elegido Canciller después de 3.',
    'Enact 6 Fascist policies, or elect Hitler Chancellor after 3.':
      'Aprueba 6 leyes fascistas, o elige a Hitler como Canciller después de 3.',
    Investigate: 'Investigar',
    'Special election': 'Elección especial',
    'Policy peek': 'Vistazo a las leyes',
    Execution: 'Ejecución',
    'The President may investigate a player': 'El Presidente puede investigar a un jugador',
    'The President will call a special election': 'El Presidente convocará una elección especial',
    'The President may look at the next three policies':
      'El Presidente puede ver las próximas tres leyes',
    'The President must execute a player': 'El Presidente debe ejecutar a un jugador',
    // seats and reasons
    President: 'Presidente',
    Chancellor: 'Canciller',
    Nominee: 'Candidato',
    Next: 'Siguiente',
    Executed: 'Ejecutado',
    Left: 'Se fue',
    'Last Chancellor': 'Último Canciller',
    'Last President': 'Último Presidente',
    'Already investigated': 'Ya investigado',
    '👻 Executed': '👻 Ejecutado',
    '✓ Not Hitler': '✓ No es Hitler',
    '🔎 Investigated': '🔎 Investigado',
    'reconnecting…': 'reconectando…',
    '✓ voted': '✓ votó',
    '✓ JA!': '✓ ¡JA!',
    '✗ NEIN!': '✗ ¡NEIN!',
    'Seat order': 'Orden de los asientos',
    // endings
    'The Liberals save the republic': 'Los liberales salvan la república',
    'Hitler is dead': 'Hitler ha muerto',
    'Hitler fled the country': 'Hitler huyó del país',
    'Fascism takes the country': 'El fascismo toma el país',
    'Hitler is Chancellor': 'Hitler es Canciller',
    'Too few left: the Liberals were closer': 'Quedan muy pocos: los liberales estaban más cerca',
    'Too few left: the Fascists were closer': 'Quedan muy pocos: los fascistas estaban más cerca',
    'The game was ended': 'El juego se terminó',
    'The Liberals win!': '¡Ganan los liberales!',
    'The Fascists win!': '¡Ganan los fascistas!',
    'No winner this time.': 'Esta vez no hay ganador.',
    'You were {role}.': 'Eras {role}.',
    // phase lines (TV and waiting phones)
    'Time ran out. A random choice was made.': 'Se acabó el tiempo. Se eligió al azar.',
    'Time ran out. A random choice was made: {name}.':
      'Se acabó el tiempo. Se eligió al azar: {name}.',
    'Legislative session: the President and Chancellor may not speak.':
      'Sesión legislativa: el Presidente y el Canciller no pueden hablar.',
    'Check your dossier. Keep it secret.': 'Revisa tu expediente. Guárdalo en secreto.',
    '{players} players · {lib} Liberals · {fas} Fascists · Hitler':
      '{players} jugadores · {lib} liberales · {fas} fascistas · Hitler',
    'President {name} is choosing a Chancellor': 'El Presidente {name} está eligiendo Canciller',
    'President {p} · Chancellor {c}': 'Presidente {p} · Canciller {c}',
    'Vote now': 'Voten ahora',
    '{n} of {m} have voted': 'Han votado {n} de {m}',
    Elected: 'Elegido',
    Rejected: 'Rechazado',
    '{ja} JA · {nein} NEIN': '{ja} JA · {nein} NEIN',
    'The election tracker moves to {n}': 'El marcador electoral sube a {n}',
    '{name} was Hitler.': '{name} era Hitler.',
    'Not Hitler': 'No es Hitler',
    '{name} is not Hitler.': '{name} no es Hitler.',
    'President {name} is reviewing three policies…': 'El Presidente {name} revisa tres leyes…',
    'Chancellor {name} is choosing one of two…': 'El Canciller {name} elige una de dos…',
    'Veto requested': 'Veto solicitado',
    'President {name} decides…': 'El Presidente {name} decide…',
    'A {party} policy is enacted': 'Se aprueba una ley: {party}',
    'Power: {power}': 'Poder: {power}',
    'Veto agreed': 'Veto aceptado',
    'Discuss…': 'Discutan…',
    'Who is telling the truth?': '¿Quién dice la verdad?',
    'Chaos!': '¡Caos!',
    'The top policy is enacted: {party}': 'Se aprueba la ley de arriba del mazo: {party}',
    'Term limits are lifted.': 'Se levantan los límites de mandato.',
    'No one left to investigate.': 'No queda nadie a quien investigar.',
    '{p} has seen {t}’s file': '{p} vio el expediente de {t}',
    'Checking the files…': 'Revisando los expedientes…',
    '{name} will be the next President': '{name} será el próximo Presidente',
    'The President has seen the top three.': 'El Presidente vio las tres de arriba.',
    '{name} was executed, and was Hitler': '{name} fue ejecutado, y era Hitler',
    '{name} was executed, and was not Hitler': '{name} fue ejecutado, y no era Hitler',
    'Last call!': '¡Última llamada!',
    // board and record
    'The board': 'El tablero',
    'Liberal policies': 'Leyes liberales',
    'Fascist policies': 'Leyes fascistas',
    Victory: 'Victoria',
    'Hitler zone': 'Zona Hitler',
    'Election tracker': 'Marcador electoral',
    'Veto unlocked': 'Veto desbloqueado',
    'Next Fascist slot: {power}': 'Siguiente casilla fascista: {power}',
    // phone
    Party: 'Partido',
    Role: 'Rol',
    Team: 'Equipo',
    Intel: 'Información',
    'Power card': 'Carta de poder',
    'Round {n}: {name} is {party}': 'Ronda {n}: {name} es {party}',
    'Round {n}: the top three were {cards}': 'Ronda {n}: las tres de arriba eran {cards}',
    Ready: 'Listo',
    'Got it': 'Entendido',
    'Choose your Chancellor': 'Elige a tu Canciller',
    'Choose a player': 'Elige a un jugador',
    'Nominate {name}': 'Nominar a {name}',
    'Tap a player': 'Toca a un jugador',
    'Vote Ja': 'Votar Ja',
    'Vote Nein': 'Votar Nein',
    'You can change your vote until the timer ends.':
      'Puedes cambiar tu voto hasta que acabe el tiempo.',
    'The policies in your hand': 'Las leyes en tu mano',
    'Hold to see the policies': 'Mantén pulsado para ver las leyes',
    'Card {n}': 'Carta {n}',
    'Tap to see the policies': 'Toca para ver las leyes',
    'Tap a policy': 'Toca una ley',
    'Discard this {party} policy': 'Descartar esta ley: {party}',
    'Enact this {party} policy': 'Aprobar esta ley: {party}',
    'Enact one policy.': 'Aprueba una ley.',
    'Request veto': 'Pedir veto',
    'Chancellor {name} requests a veto.': 'El Canciller {name} pide un veto.',
    Agree: 'Aceptar',
    Refuse: 'Rechazar',
    'Both policies will be thrown away, and the tracker moves up one.':
      'Las dos leyes se descartan y el marcador sube uno.',
    'The next three policies': 'Las próximas tres leyes',
    Done: 'Listo',
    'They go back in the same order.': 'Vuelven en el mismo orden.',
    'This can’t be undone. Execute {name}?': 'No se puede deshacer. ¿Ejecutar a {name}?',
    '{power}: {name}': '{power}: {name}',
    'Last call! Choose now.': '¡Última llamada! Elige ya.',
    'You were executed. Ghosts can’t talk or vote.':
      'Te ejecutaron. Los fantasmas no hablan ni votan.',
    'You left this game.': 'Saliste de este juego.',
    'You’re in as soon as this one ends.': 'Entras en cuanto termine este.',
    // Parliament Noir (M2 visuals)
    'A new parliament': 'Un nuevo parlamento',
    CHAOS: 'CAOS',
    CLASSIFIED: 'CONFIDENCIAL',
    Chaos: 'Caos',
    Classified: 'Confidencial',
    'Close your dossier': 'Cerrar tu expediente',
    Dossier: 'Expediente',
    ELECTED: 'ELEGIDO',
    EXECUTED: 'EJECUTADO',
    'Election tracker: {n} of 3': 'Marcador electoral: {n} de 3',
    Extra: 'Extra',
    'Fascist policy': 'Ley fascista',
    'Final edition': 'Edición final',
    'Hold to read': 'Mantén pulsado para leer',
    'Keep it secret. Tap the folder to open or close it.':
      'Guárdalo en secreto. Toca la carpeta para abrirla o cerrarla.',
    'Liberal policy': 'Ley liberal',
    'NOT HITLER': 'NO ES HITLER',
    'No governments yet.': 'Aún no hay gobiernos.',
    'Open your dossier': 'Abrir tu expediente',
    'Parliament Record': 'Registro del Parlamento',
    Policy: 'Ley',
    REJECTED: 'RECHAZADO',
    'Read your dossier': 'Lee tu expediente',
    'Session {n}': 'Sesión {n}',
    'Special edition': 'Edición especial',
    'Tap a card to choose it · tap here to hide them':
      'Toca una carta para elegirla · toca aquí para ocultarlas',
    'Tap here to hide them': 'Toca aquí para ocultarlas',
    'Tap to close': 'Toca para cerrar',
    'Tap to read': 'Toca para leer',
    'The Evening Republic': 'La República de la Tarde',
    'The Evening Republic · a new parliament sits tonight':
      'La República de la Tarde · esta noche se reúne un nuevo parlamento',
    'VETO REQUESTED': 'VETO SOLICITADO',
    Veto: 'Veto',
    You: 'Tú',
    'You are the President': 'Eres el Presidente',
    'Your power': 'Tu poder',
    discarded: 'descartadas',
    'in the deck': 'en el mazo',
    'Session · say nothing': 'Sesión · ni una palabra',
    'Discard one policy': 'Descarta una ley',
    'The other two go to Chancellor {name}.': 'Las otras dos van al Canciller {name}.',
  },
};
