// Fake-Out's words in Spanish, keyed by the English sentence (ADR-044). Screens write `L('…')` from
// `useT(STRINGS)`; the picker reads the manifest's lines from here too, and
// scripts/i18n-coverage.test.ts fails until each has its Spanish. `{name}` marks a placeholder.
// Content (the facts in content/) stays in English.
import type { Strings } from '@partybox/game-sdk/ui';

export const STRINGS: Strings = {
  es: {
    // manifest.json — the game picker
    'Write a fake answer. Find the real one.': 'Escribe una respuesta falsa. Encuentra la real.',
    'A strange true fact appears with a blank. Everyone types a fake answer that sounds real, then all the answers are mixed with the truth and everyone picks the one they believe. Score for finding the truth and for every player your fake fools. The last question is worth double.':
      'Aparece un dato real y extraño con un hueco. Cada quien escribe una respuesta falsa que suene real; luego todas se mezclan con la verdad y cada quien elige la que cree. Sumas por encontrar la verdad y por cada jugador que cae con tu mentira. La última pregunta vale doble.',
    Questions: 'Preguntas',
    'How many facts to play; the last one is the Final Fake-Out':
      'Cuántos datos jugar; el último es el Engaño Final',
    'Lying time': 'Tiempo para mentir',
    'Seconds to write a fake answer': 'Segundos para escribir una respuesta falsa',
    'Picking time': 'Tiempo para elegir',
    'Seconds to pick the answer you believe': 'Segundos para elegir la respuesta que crees',
    'Final Fake-Out': 'Engaño Final',
    'The last question doubles all points': 'La última pregunta duplica todos los puntos',
    'Suggest a lie': 'Sugerir una mentira',
    'Show the 💡 button that offers two ready-made fakes':
      'Mostrar el botón 💡 que ofrece dos mentiras listas',
    Likes: 'Me gusta',
    'Let players 👍 the funniest answers while they pick':
      'Deja que los jugadores den 👍 a las respuestas más graciosas mientras eligen',
    Categories: 'Categorías',
    'Tick the categories to play; nothing ticked plays them all':
      'Marca las categorías a jugar; sin marcar se juegan todas',
    Animals: 'Animales',
    History: 'Historia',
    Food: 'Comida',
    Science: 'Ciencia',
    Geography: 'Geografía',
    'Weird laws': 'Leyes raras',
    Sports: 'Deportes',
    Inventions: 'Inventos',
    Space: 'El espacio',
    'The human body': 'El cuerpo humano',
    Words: 'Palabras',
    Holidays: 'Fiestas',
    'Drinking (spicy)': 'Bebida (picante)',
    'Dating (spicy)': 'Citas (picante)',
    'Spicy facts': 'Datos picantes',
    'Mix in adult facts (drinking, dating, bawdy history; never explicit)':
      'Mezcla datos para adultos (bebida, citas, historia pícara; nunca explícitos)',
    Reader: 'Lector',
    'The voice that reads each fact and answer aloud':
      'La voz que lee en voz alta cada dato y cada respuesta',
    'No reader': 'Sin lector',
    'Old British Man': 'Señor británico mayor',
    'Young British Man': 'Joven británico',
    'American Woman': 'Mujer estadounidense',
    'Soft-Spoken Woman': 'Mujer de voz suave',
    Original: 'Original',
    // how to play (TV intro + phone)
    'A strange true fact appears with a blank. Type a fake answer that sounds real.':
      'Aparece un dato real y extraño con un hueco. Escribe una respuesta falsa que suene real.',
    'All answers are mixed with the truth. Pick the one you think is real.':
      'Todas las respuestas se mezclan con la verdad. Elige la que crees que es real.',
    'Score for finding the truth, and for every player your fake fools.':
      'Sumas por encontrar la verdad y por cada jugador que cae con tu mentira.',
    'I’m ready': 'Estoy listo',
    'Start now': 'Empezar ya',
    'Ready! Waiting for the others…': '¡Listo! Esperando a los demás…',
    'Tap I’m ready on your phone · {n} / {total} ready':
      'Toca «Estoy listo» en tu teléfono · {n} / {total} listos',
    ready: 'listo',
    'not ready': 'no listo',
    'Everyone is ready!': '¡Todos listos!',
    'The facts and answers are in English.': 'Los datos y las respuestas están en inglés.',
    // TV
    'Final Fake-Out · double points': 'Engaño Final · puntos dobles',
    'Question {n} of {total}': 'Pregunta {n} de {total}',
    Drinking: 'Bebida',
    Dating: 'Citas',
    'Write a fake answer on your phone': 'Escribe una respuesta falsa en tu teléfono',
    'Which one is the truth?': '¿Cuál es la verdad?',
    '{n} / {total} lies in': '{n} / {total} mentiras',
    '{n} / {total} picked': '{n} / {total} eligieron',
    'waiting for': 'esperando a',
    'picked by': 'lo eligió',
    'Nobody picked it': 'Nadie lo eligió',
    'written by': 'lo escribió',
    '{n} likes': '{n} me gusta',
    'TRUTH ✓': 'VERDAD ✓',
    'LIE ✗': 'MENTIRA ✗',
    'PARTYBOX LIE 🤖': 'MENTIRA DE PARTYBOX 🤖',
    'Nobody scores for this one': 'Nadie suma con esta',
    'Nobody found the truth!': '¡Nadie encontró la verdad!',
    '+{pts} each': '+{pts} cada uno',
    'Nobody fell for…': 'Nadie cayó con…',
    blank: 'hueco',
    'After question {n} of {total}': 'Tras la pregunta {n} de {total}',
    'After the Final Fake-Out': 'Tras el Engaño Final',
    'Final scores': 'Puntuación final',
    'Scores so far': 'Puntuación hasta ahora',
    'How the points came': 'De dónde salieron los puntos',
    'Nobody scored this time': 'Nadie sumó esta vez',
    'Next: the Final Fake-Out — double points!': 'Ahora: el Engaño Final, ¡puntos dobles!',
    '+{pts} truth': '+{pts} verdad',
    '+{pts} fooled {n}': '+{pts} engañó a {n}',
    '×2 final': '×2 final',
    // phone
    'Start writing now': 'Empezar a escribir ya',
    'Think of a fake answer that sounds real…': 'Piensa una respuesta falsa que suene real…',
    'Listen to the TV — then think of a fake answer…':
      'Escucha la TV y piensa una respuesta falsa…',
    'Your fake answer': 'Tu respuesta falsa',
    'A fake answer that sounds real…': 'Una respuesta falsa que suene real…',
    'Make it sound real. Spelling counts!': 'Que suene real. ¡La ortografía cuenta!',
    "That's actually the truth! Write a fake one.": '¡Esa es la verdad! Escribe una falsa.',
    'Keep it under 40 characters.': 'Máximo 40 caracteres.',
    'Type a fake answer.': 'Escribe una respuesta falsa.',
    'Tap one to use it': 'Toca una para usarla',
    'Lock it in': 'Confirmar',
    Change: 'Cambiar',
    'Locked in': 'Confirmada',
    'Waiting for the others…': 'Esperando a los demás…',
    'Waiting for the others — watch the TV': 'Esperando a los demás. Mira la TV',
    'Pick the truth': 'Elige la verdad',
    '👍 = funniest (optional)': '👍 = la más graciosa (opcional)',
    'Your lie: {lie}': 'Tu mentira: {lie}',
    'Like {lie}': 'Me gusta {lie}',
    'Unlike {lie}': 'Quitar me gusta de {lie}',
    'Picked! Tap another to change your mind.': '¡Elegida! Toca otra para cambiar de opinión.',
    'Watch the TV': 'Mira la TV',
    "You fell for {who}'s {lie}": 'Caíste con {lie} de {who}',
    'You fell for a PartyBox lie: {lie}': 'Caíste con una mentira de PartyBox: {lie}',
    'You found the truth! +{pts}': '¡Encontraste la verdad! +{pts}',
    'Your {lie} fooled {who} +{pts}': 'Tu {lie} engañó a {who} +{pts}',
    'Nobody fell for your {lie}': 'Nadie cayó con tu {lie}',
    '{a} and {b}': '{a} y {b}',
    'all tied': 'todos empatados',
    '#{rank} of {count}': 'n.º {rank} de {count}',
    '{place} · {score} points': '{place} · {score} puntos',
    'No points this question': 'Sin puntos en esta pregunta',
    'Next question': 'Siguiente pregunta',
    'See results': 'Ver resultados',
    'Watching this one': 'Mirando esta partida',
    "You're in as soon as this game ends.": 'Entras en cuanto termine esta partida.',
    'One moment…': 'Un momento…',
    // awards (written by the server, translated on the results screens)
    '🎭 Master Liar': '🎭 Gran Mentiroso',
    '🔍 Truth Detector': '🔍 Detector de Verdades',
    '👍 Crowd Favourite': '👍 Favorito del Público',
    '🍀 Lucky Guess': '🍀 Chiripa',
    '🤖 Fooled by the House': '🤖 Engañado por la Casa',
    'Players fooled: {n}': 'Jugadores engañados: {n}',
    'Truths found: {n}': 'Verdades encontradas: {n}',
    'Likes received: {n}': 'Me gusta recibidos: {n}',
    'Truths typed as lies: {n}': 'Verdades escritas como mentira: {n}',
    'PartyBox lies picked: {n}': 'Mentiras de PartyBox elegidas: {n}',
  },
};
