// Echo's words in other languages, keyed by the English sentence (ADR-044). The shell's picker
// reads the manifest's tagline, description and setting labels from here too;
// scripts/i18n-coverage.test.ts fails until each has its Spanish. Content (the words and clues)
// stays in English.
import type { Strings } from '@partybox/game-sdk/ui';

export const STRINGS: Strings = {
  es: {
    // manifest.json — the game picker
    'One clue each. Same clue? Both vanish.':
      'Una pista cada uno. ¿Pista repetida? Desaparecen las dos.',
    "A co-op word game. One player guesses; everyone else sees the secret word and writes a one-word clue without peeking at each other's. Clues that match cancel out before the guesser sees them, so be clever, not obvious. A wrong guess burns the next word too. The whole group wins or loses together.":
      'Un juego de palabras cooperativo. Una persona adivina; las demás ven la palabra secreta y escriben una pista de una sola palabra sin mirar las de los demás. Las pistas que coinciden se anulan antes de que quien adivina las vea, así que sé ingenioso, no obvio. Un error también quema la palabra siguiente. Todo el grupo gana o pierde junto.',
    Words: 'Palabras',
    'How many words are in the deck': 'Cuántas palabras tiene el mazo',
    'Clue time': 'Tiempo para pistas',
    'Seconds to write a clue': 'Segundos para escribir una pista',
    'Guess time': 'Tiempo para adivinar',
    'Seconds for the guesser': 'Segundos para quien adivina',
    'Echo check': 'Revisión de ecos',
    'Clue-givers review the echoes before the guesser sees the clues':
      'Quienes dan pistas revisan los ecos antes de que quien adivina vea las pistas',
    Categories: 'Categorías',
    'Tick the kinds of words to play; nothing ticked plays them all':
      'Marca los tipos de palabras a jugar; sin marcar se juegan todos',
    Animals: 'Animales',
    Food: 'Comida',
    Objects: 'Objetos',
    Places: 'Lugares',
    Jobs: 'Oficios',
    Nature: 'Naturaleza',
    Activities: 'Actividades',
    Fantasy: 'Fantasía',
    Sports: 'Deportes',
    'Around the house': 'En casa',
    'Spicy words': 'Palabras picantes',
    'Adds grown-up words (hangovers, first dates), never explicit':
      'Añade palabras para adultos (resacas, primeras citas), nunca explícitas',
    Reader: 'Lector',
    'Who reads the surviving clues aloud': 'Quién lee en voz alta las pistas que sobreviven',
    'No reader': 'Sin lector',
    'Old British Man': 'Señor británico mayor',
    'Young British Man': 'Joven británico',
    'American Woman': 'Mujer estadounidense',
    'Soft-Spoken Woman': 'Mujer de voz suave',
    Original: 'Original',
    // server text: the VIP's Next labels, awards
    "Let's go": '¡Vamos!',
    'Close the clues': 'Cerrar las pistas',
    'Looks good for everyone': 'Todo bien para todos',
    'Count it as a pass': 'Contarlo como paso',
    'Next word': 'Siguiente palabra',
    'See results': 'Ver resultados',
    '🗝️ Key Clue': '🗝️ Pista clave',
    'Most clues that survived on words the team got':
      'Más pistas que sobrevivieron en palabras acertadas',
    '🔁 Echo Chamber': '🔁 Cámara de eco',
    'Most clues that vanished': 'Más pistas que desaparecieron',
    '🎯 Sharp Guesser': '🎯 Buen ojo',
    'Most right guesses': 'Más aciertos',
    '🙈 Bold Guess': '🙈 Pura osadía',
    'Most wrong guesses': 'Más fallos',
    // intro (TV + phone)
    Echo: 'Echo',
    'One player guesses; everyone else sees the secret word and writes a one-word clue.':
      'Una persona adivina; las demás ven la palabra secreta y escriben una pista de una palabra.',
    'Clues that match each other vanish before the guesser sees them.':
      'Las pistas que coinciden desaparecen antes de que quien adivina las vea.',
    "Guess the word from what's left. The whole group wins or loses together.":
      'Adivina la palabra con lo que queda. Todo el grupo gana o pierde junto.',
    'Deck: {n} words': 'Mazo: {n} palabras',
    'How to play': 'Cómo se juega',
    // TV
    'Word {n} of {total}': 'Palabra {n} de {total}',
    '{left} left, {won} won, {lost} lost': 'quedan {left}, ganadas {won}, perdidas {lost}',
    left: 'quedan',
    won: 'ganadas',
    lost: 'perdidas',
    '{name} is guessing': '{name} adivina',
    'Everyone else: one clue each. No peeking!': 'Los demás: una pista cada uno. ¡Sin mirar!',
    'Everyone else: two different clues each. No peeking!':
      'Los demás: dos pistas distintas cada uno. ¡Sin mirar!',
    'Listening for echoes…': 'Escuchando los ecos…',
    'Word swapped!': '¡Palabra cambiada!',
    "{name}, what's the word?": '{name}, ¿cuál es la palabra?',
    'No clues!': '¡No hay pistas!',
    '🔒 {name} has an answer…': '🔒 {name} ya tiene respuesta…',
    echo: 'eco',
    "Total echo! {name}'s on their own.": '¡Eco total! {name} va por su cuenta.',
    'The word was': 'La palabra era',
    '{name} passed': '{name} pasó',
    '{name} guessed “{guess}”': '{name} dijo «{guess}»',
    '✓ Got it!': '✓ ¡Acertó!',
    '✗ Not quite': '✗ Casi',
    PASS: 'PASA',
    'Counted by the VIP': 'Contado por el VIP',
    '…and it burned the next word.': '…y quemó la siguiente palabra.',
    '…and it cost a word we had won.': '…y costó una palabra que ya teníamos.',
    '{won} of {total} words': '{won} de {total} palabras',
    'a lost word': 'una palabra perdida',
    Flawless: 'Perfecto',
    Brilliant: 'Brillante',
    Great: 'Genial',
    Solid: 'Bien',
    'Warming up': 'Calentando',
    'Try again!': '¡Otra vez!',
    // phone: clue
    'Hold to see the word': 'Mantén para ver la palabra',
    'One word to help {name}': 'Una palabra para ayudar a {name}',
    'Two different words to help {name}': 'Dos palabras distintas para ayudar a {name}',
    'Clue {n}': 'Pista {n}',
    'Your clue': 'Tu pista',
    'Type a clue first.': 'Escribe una pista primero.',
    'Keep it under 20 letters.': 'Menos de 20 letras.',
    'One word only.': 'Solo una palabra.',
    "That's the word! Try another.": '¡Esa es la palabra! Prueba otra.',
    'Too close to the word. Try another.': 'Demasiado parecida a la palabra. Prueba otra.',
    'Two different words, please.': 'Dos palabras distintas, por favor.',
    'Two clues, please.': 'Dos pistas, por favor.',
    '✓ Good to go': '✓ Lista',
    'One word, no spaces': 'Una palabra, sin espacios',
    'Lock it in': 'Confirmar',
    'Sending…': 'Enviando…',
    Change: 'Cambiar',
    'Locked in. Waiting for the others…': 'Confirmada. Esperando a los demás…',
    "🤔 Don't know this word": '🤔 No conozco esta palabra',
    '🤔 Asked for a new word…': '🤔 Pediste otra palabra…',
    // phone: check
    'Check the echoes': 'Revisa los ecos',
    'Struck-through clues vanish. Tap if the game got one wrong.':
      'Las pistas tachadas desaparecen. Toca si el juego se equivocó.',
    'No echoes. Tap Same word if two clues really match.':
      'Sin ecos. Toca Misma palabra si dos pistas coinciden de verdad.',
    'Now tap the clue it matches': 'Ahora toca la pista con la que coincide',
    '🔇 echo': '🔇 eco',
    'Not the same ✋': 'No son iguales ✋',
    'Same after all': 'Sí eran iguales',
    'Same word ✋': 'Misma palabra ✋',
    Cancel: 'Cancelar',
    'Looks good': 'Todo bien',
    // phone: guess
    'The clues': 'Las pistas',
    'Total echo!': '¡Eco total!',
    '🔇 1 clue echoed away': '🔇 1 pista se perdió en el eco',
    '🔇 {n} clues echoed away': '🔇 {n} pistas se perdieron en el eco',
    '{name} is guessing…': '{name} está adivinando…',
    "What's the word?": '¿Cuál es la palabra?',
    'Your guess': 'Tu respuesta',
    Pass: 'Pasar',
    Guess: 'Adivinar',
    'Sent!': '¡Enviado!',
    'A wrong guess burns the next word too. Pass if unsure.':
      'Un error también quema la siguiente palabra. Pasa si no estás seguro.',
    // phone: waiting and result
    "You're guessing!": '¡Te toca adivinar!',
    'No peeking at other phones. They are writing clues…':
      'No mires otros teléfonos. Están escribiendo pistas…',
    'No peeking at other phones. They are checking for echoes…':
      'No mires otros teléfonos. Están revisando los ecos…',
    'Watch the TV': 'Mira la TV',
    'Thanks for playing!': '¡Gracias por jugar!',
    '✓ Got it! 1 won so far': '✓ ¡Acertó! 1 ganada hasta ahora',
    '✓ Got it! {n} won so far': '✓ ¡Acertó! {n} ganadas hasta ahora',
    '✗ Not quite. The next word burned too': '✗ Casi. También se quemó la siguiente palabra',
    '✗ Not quite. It cost a word we had won': '✗ Casi. Costó una palabra que ya teníamos',
    'Pass. On to the next': 'Pasó. A la siguiente',
    '✓ That counts': '✓ Cuenta',
  },
};
