// Imposter's in-game sentences in Spanish (TV, phone, PhoneStage), keyed by the English.
export const STRINGS_ES_PLAY: Record<string, string> = {
  // how to play
  'How to play': 'Cómo se juega',
  "Let's go": '¡Vamos!',
  'Everyone gets the secret word except the imposter, who only knows the category.':
    'Todos reciben la palabra secreta menos el impostor, que solo sabe la categoría.',
  'Everyone types one word about it. The imposter has to fake it.':
    'Cada quien escribe una palabra sobre ella. El impostor tiene que fingir.',
  'Vote out the imposter. A caught imposter can still steal it by guessing the word.':
    'Voten para sacar al impostor. Si lo atrapan, aún puede robarse la ronda adivinando la palabra.',
  // rounds and the table
  'Round {n} of {of}': 'Ronda {n} de {of}',
  'clue round {n} of {of}': 'ronda de pistas {n} de {of}',
  '2 imposters': '2 impostores',
  'Category: {c}': 'Categoría: {c}',
  'No hint this round': 'Sin pista esta ronda',
  'Check your secret card': 'Mira tu carta secreta',
  'Type one word': 'Escriban una palabra',
  'Type one more word': 'Escriban una palabra más',
  'Clues are in': 'Llegaron las pistas',
  "Talk it over. Who's faking?": 'Hablen. ¿Quién está fingiendo?',
  "Next on the VIP's phone": 'Lo siguiente, en el teléfono del VIP',
  'Vote on your phone': 'Voten en su teléfono',
  'Vote on your phone: pick 2': 'Voten en su teléfono: elijan 2',
  'The votes': 'Los votos',
  'The runoff': 'El desempate',
  'Tie! Vote again: {names}': '¡Empate! Voten otra vez: {names}',
  // accusation, last chance, reveal
  'The room accuses…': 'La sala acusa a…',
  IMPOSTER: 'IMPOSTOR',
  INNOCENT: 'INOCENTE',
  imposter: 'impostor',
  innocent: 'inocente',
  "{name}'s last chance": 'Última oportunidad de {name}',
  '{name} is typing': '{name} está escribiendo',
  '{name} is choosing': '{name} está eligiendo',
  '{name} has guessed': '{name} ya respondió',
  '{name} is guessing…': '{name} está adivinando…',
  'Guess is in…': 'Ya adivinó…',
  'Last chance': 'Última oportunidad',
  'The word was': 'La palabra era',
  'The imposter left the building.': 'El impostor abandonó el edificio.',
  '{name} guessed {word} · stolen! +3': '{name} dijo {word} · ¡robada! +3',
  '{name} guessed {word} · no luck': '{name} dijo {word} · sin suerte',
  'Counted by the VIP': 'El VIP la dio por buena',
  'The imposter escapes!': '¡El impostor escapa!',
  'After round {n} of {of}': 'Después de la ronda {n} de {of}',
  // the secret card
  'Your secret card': 'Tu carta secreta',
  'Hold to see your word': 'Mantén presionado para ver tu palabra',
  'Hold to peek': 'Mantén para ver',
  'Tap to see it; it hides again by itself': 'Tócala para verla; se vuelve a ocultar sola',
  'Keep it close — neighbours peek': 'Tápala bien: los vecinos espían',
  'Your word': 'Tu palabra',
  "You're the": 'Eres el',
  "Blend in. Don't get caught.": 'Pasa desapercibido. Que no te atrapen.',
  "There are 2 imposters. You don't know the other one.":
    'Hay 2 impostores. No sabes quién es el otro.',
  'Got it': 'Entendido',
  'Got it ✓': 'Entendido ✓',
  'Waiting for the others…': 'Esperando a los demás…',
  // clues
  'One word about the secret word': 'Una palabra sobre la palabra secreta',
  'one word': 'una palabra',
  'Your clue': 'Tu pista',
  'Lock it in': 'Confirmar',
  'Locked in:': 'Confirmada:',
  Change: 'Cambiar',
  'Clues so far': 'Pistas hasta ahora',
  'Type a clue first.': 'Primero escribe una pista.',
  'Keep it to 20 letters.': 'Máximo 20 letras.',
  'One word only.': 'Solo una palabra.',
  "That's the word! Try another.": '¡Esa es la palabra! Prueba otra.',
  'Too close to the word. Try another.': 'Demasiado parecida a la palabra. Prueba otra.',
  'Someone already said that.': 'Alguien ya dijo eso.',
  // talk and vote
  'Start the vote': 'Empezar la votación',
  'The VIP starts the vote.': 'El VIP inicia la votación.',
  'Who is the imposter?': '¿Quién es el impostor?',
  'Tie! Vote again': '¡Empate! Vota otra vez',
  'Pick 1': 'Elige 1',
  'Pick 2': 'Elige 2',
  'Voted ✓': 'Votaste ✓',
  Vote: 'Votar',
  'Vote for these 2': 'Votar por estos 2',
  Suspects: 'Sospechosos',
  'Press and hold a face to read all their clues.':
    'Mantén presionada una cara para leer todas sus pistas.',
  'Voting…': 'Votando…',
  // last chance and results
  'Caught!': '¡Atrapado!',
  "Last chance: what's the word?": 'Última oportunidad: ¿cuál es la palabra?',
  Guess: 'Adivinar',
  'Your guess': 'Tu respuesta',
  'You escaped!': '¡Escapaste!',
  'Caught, but you stole it': 'Te atraparon, pero te la robaste',
  'They got you': 'Te atraparon',
  'You caught the imposter and read it right': 'Atraparon al impostor y lo leíste bien',
  'The room caught the imposter': 'La sala atrapó al impostor',
  'You read it right': 'Lo leíste bien',
  'The imposter got away': 'El impostor se escapó',
  '#{rank} of {count} · {score} points': '#{rank} de {count} · {score} puntos',
  '+4 escaped · {names}': '+4 escapó · {names}',
  '+3 stole · {names}': '+3 robó · {names}',
  '+2 caught · {n} players': '+2 atrapado · {n} jugadores',
  '+1 read · {n} players': '+1 bien leído · {n} jugadores',
  '✓ That counts': '✓ Vale',
  Scores: 'Puntajes',
  'Next round': 'Siguiente ronda',
  'See results': 'Ver resultados',
  'Watch the TV': 'Mira la TV',
  'in English': 'en inglés',
  'You caught {name}, but they stole the word': 'Atraparon a {name}, pero se robó la palabra',
  'Here it comes…': 'Ahí viene…',
  'You joined mid-game': 'Entraste a mitad del juego',
  'Watch the TV — you are in the next game.': 'Mira la TV: juegas en la siguiente partida.',
};
