// GENERATED by scripts/gen-registry.ts — do not edit
import type { GameClientModule } from '@partybox/game-sdk';
// No games yet. Add one with: pnpm new-game <id>

export const clientGames: Readonly<Record<string, GameClientModule>> = {
};
