// GENERATED by scripts/gen-registry.ts — do not edit
import type { GameClientModule } from '@partybox/game-sdk';
import { clientModule as lightningRound } from '../../../games/lightning-round/client/index';

export const clientGames: Readonly<Record<string, GameClientModule>> = {
  'lightning-round': lightningRound,
};
