// GENERATED by scripts/gen-registry.ts — do not edit
import type { GameClientModule } from '@partybox/game-sdk';
import { clientModule as bingo } from '../../../games/bingo/client/index';
import { clientModule as blanks } from '../../../games/blanks/client/index';
import { clientModule as brokenPencil } from '../../../games/broken-pencil/client/index';
import { clientModule as lightningRound } from '../../../games/lightning-round/client/index';
import { clientModule as tuneIn } from '../../../games/tune-in/client/index';
import { clientModule as wisecrack } from '../../../games/wisecrack/client/index';

export const clientGames: Readonly<Record<string, GameClientModule>> = {
  'bingo': bingo,
  'blanks': blanks,
  'broken-pencil': brokenPencil,
  'lightning-round': lightningRound,
  'tune-in': tuneIn,
  'wisecrack': wisecrack,
};
