// GENERATED by scripts/gen-registry.ts — do not edit
import type { AnyGameDefinition } from '@partybox/shared';
import { game as bingo } from '../../../games/bingo/server/index';
import { game as blanks } from '../../../games/blanks/server/index';
import { game as brokenPencil } from '../../../games/broken-pencil/server/index';
import { game as fakeOut } from '../../../games/fake-out/server/index';
import { game as lightningRound } from '../../../games/lightning-round/server/index';
import { game as wisecrack } from '../../../games/wisecrack/server/index';

export const serverGames: Readonly<Record<string, AnyGameDefinition>> = {
  'bingo': bingo,
  'blanks': blanks,
  'broken-pencil': brokenPencil,
  'fake-out': fakeOut,
  'lightning-round': lightningRound,
  'wisecrack': wisecrack,
};
