// Generates the explicit game registries (ADR-003):
//   packages/server/src/games.generated.ts  -> every games/<id>/server/index.ts `game`
//   packages/client/src/games.generated.ts  -> every games/<id>/client/{phone,tv,settings}-entry.ts, lazily
// Usage: pnpm gen-registry [--check]   (--check exits 1 when the files on disk are stale)
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fail } from './lib/run';
import {
  listGameFolders,
  missingGameFiles,
  readManifest,
  REPO_ROOT,
  toIdentifier,
} from './lib/games';

const HEADER = '// GENERATED by scripts/gen-registry.ts — do not edit\n';

interface Target {
  file: string;
  render: (games: { id: string; ident: string }[]) => string;
}

const targets: Target[] = [
  {
    file: join(REPO_ROOT, 'packages/server/src/games.generated.ts'),
    render: (games) =>
      `${HEADER}import type { AnyGameDefinition } from '@partybox/shared';\n` +
      (games.length === 0 ? '// No games yet. Add one with: pnpm new-game <id>\n' : '') +
      games
        .map((g) => `import { game as ${g.ident} } from '../../../games/${g.id}/server/index';\n`)
        .join('') +
      // ADR-049: each game's manifest sentences in Spanish (the catalog, About, the settings form).
      games
        .map(
          (g) =>
            `import ${g.ident}Es from '../../../games/${g.id}/manifest.es.json' with { type: 'json' };\n`,
        )
        .join('') +
      `\nexport const serverGames: Readonly<Record<string, AnyGameDefinition>> = {\n` +
      games.map((g) => `  '${g.id}': ${g.ident},\n`).join('') +
      `};\n` +
      `\nexport const serverGameText: Readonly<Record<string, Readonly<Record<string, Readonly<Record<string, string>>>>>> = {\n` +
      games.map((g) => `  '${g.id}': { es: ${g.ident}Es },\n`).join('') +
      `};\n`,
  },
  {
    file: join(REPO_ROOT, 'packages/client/src/games.generated.ts'),
    render: (games) =>
      // ADR-050: nothing of a game is imported here — each surface is a dynamic import, so the
      // bundler gives every game its own phone and TV downloads and the entry never grows.
      `${HEADER}import type { GameLoaders } from '@partybox/game-sdk';\n` +
      (games.length === 0 ? '// No games yet. Add one with: pnpm new-game <id>\n' : '') +
      `\nexport const gameLoaders: Readonly<Record<string, GameLoaders>> = {\n` +
      games
        .map((g) => {
          const at = `../../../games/${g.id}/client`;
          const settings = existsSync(join(REPO_ROOT, 'games', g.id, 'client', 'settings-entry.ts'))
            ? `    settings: () => import('${at}/settings-entry').then((m) => m.settings),\n`
            : '';
          return (
            `  '${g.id}': {\n` +
            `    phone: () => import('${at}/phone-entry').then((m) => m.phone),\n` +
            `    tv: () => import('${at}/tv-entry').then((m) => m.tv),\n` +
            settings +
            `  },\n`
          );
        })
        .join('') +
      `};\n`,
  },
];

function collectGames(): { id: string; ident: string }[] {
  const problems: string[] = [];
  const games: { id: string; ident: string }[] = [];
  for (const folder of listGameFolders()) {
    const missing = missingGameFiles(folder.dir);
    if (missing.length > 0) problems.push(`games/${folder.id} is missing: ${missing.join(', ')}`);
    const manifest = readManifest(folder.dir);
    // `_template` carries id `template`: leading underscores mean "not registered".
    if (manifest['id'] !== folder.id.replace(/^_/, ''))
      problems.push(`games/${folder.id}/manifest.json has id "${String(manifest['id'])}"`);
    if (folder.registered) games.push({ id: folder.id, ident: toIdentifier(folder.id) });
  }
  if (problems.length > 0) fail(`gen-registry:\n  ${problems.join('\n  ')}`);
  return games;
}

function main(): void {
  const check = process.argv.includes('--check');
  const games = collectGames();
  let stale = 0;
  for (const target of targets) {
    const next = target.render(games);
    const current = existsSync(target.file) ? readFileSync(target.file, 'utf8') : null;
    if (current === next) continue;
    if (check) {
      stale += 1;
      console.error(`stale: ${target.file}`);
    } else {
      writeFileSync(target.file, next);
      console.log(`wrote ${target.file}`);
    }
  }
  if (check && stale > 0) fail('registry is stale — run: pnpm gen-registry');
  if (check) console.log(`registry current (${games.length} game${games.length === 1 ? '' : 's'})`);
}

main();
