// Nightfall's words in Spanish, keyed by the English sentence (ADR-044). Screens write `L('…')`;
// sentences the server writes (narrator lines, role names, reports) render through `L.sent(text)`,
// which also matches the `{name}` entries. Content (bot lines) stays in English.
import type { Strings } from '@partybox/game-sdk/ui';
import { STRINGS_UI_ES } from './strings-ui';

export const STRINGS: Strings = {
  es: {
    // Words the screens share with the settings (the settings' own Spanish: manifest.es.json)
    Wolves: 'Lobos',
    'Town board': 'Tablón del pueblo',
    Night: 'Noche',
    Day: 'Día',
    Vote: 'Votación',

    // flavours.json — village
    Wolf: 'Lobo',
    Seer: 'Vidente',
    Seers: 'Videntes',
    Doctor: 'Médico',
    Doctors: 'Médicos',
    Villager: 'Aldeano',
    Villagers: 'Aldeanos',
    Hunter: 'Cazador',
    Hunters: 'Cazadores',
    Jester: 'Bufón',
    Jesters: 'Bufones',
    'Each night, choose a victim with your pack.': 'Cada noche, elige una víctima con tu manada.',
    'Each night, check one player: wolf or not.': 'Cada noche, investiga a alguien: ¿lobo o no?',
    'Each night, protect one player from the wolves.':
      'Cada noche, protege a alguien de los lobos.',
    'Find the wolves and vote them out.': 'Encuentra a los lobos y expúlsalos.',
    'When you die, take someone with you.': 'Cuando mueras, llévate a alguien contigo.',
    'Get the village to vote you out, and you win.': 'Si el pueblo te expulsa, ganas tú.',
    'A wolf!': '¡Un lobo!',
    'The seer.': 'La vidente.',
    'The doctor.': 'El médico.',
    'A villager.': 'Un aldeano.',
    'The hunter.': 'El cazador.',
    'The jester!': '¡El bufón!',
    'The wolves': 'Los lobos',
    'The village': 'El pueblo',
    'The jester': 'El bufón',
    'a wolf': 'un lobo',
    'the wolves': 'los lobos',
    seer: 'vidente',
    villager: 'aldeano',
    "Who's a wolf?": '¿Quién es lobo?',
    'Your pack': 'Tu manada',
    'Pack picks': 'Elecciones de la manada',
    '{name} is a WOLF': '{name} es un LOBO',
    '{name} is not a wolf': '{name} no es lobo',
    'The pack chose {name}': 'La manada eligió a {name}',
    "Choose tonight's victim": 'Elige la víctima de esta noche',
    "That's your packmate!": '¡Es de tu manada!',
    'Night falls. Everyone, look at your phone.': 'Cae la noche. Todos, miren su teléfono.',
    'The village sleeps.': 'El pueblo duerme.',
    'Dawn breaks.': 'Amanece.',
    'Everyone survived the night!': '¡Todos sobrevivieron a la noche!',
    "Discuss. Who's a wolf?": 'A discutir. ¿Quién es lobo?',
    'Time to vote.': 'Hora de votar.',
    'The votes are in.': 'Ya están los votos.',
    "It's a tie. Vote again.": 'Empate. Voten otra vez.',
    "The village couldn't agree.": 'El pueblo no se puso de acuerdo.',
    'The hunter takes aim…': 'El cazador apunta…',
    'Ghosts, stay silent.': 'Fantasmas, silencio.',
    "Ghosts, stay silent. Discuss. Who's a wolf?":
      'Fantasmas, silencio. A discutir. ¿Quién es lobo?',
    'The wolves win.': 'Ganan los lobos.',
    'The village wins!': '¡Gana el pueblo!',
    'The jester fooled you all!': '¡El bufón los engañó a todos!',
    '{name} did not survive the night.': '{name} no sobrevivió a la noche.',
    '{name} was…': '{name} era…',
    '{name} packed up and left the village.': '{name} hizo las maletas y dejó el pueblo.',
    'The hunter took {name} down.': 'El cazador se llevó a {name}.',
    "{name}'s last words.": 'Las últimas palabras de {name}.',

    // flavours.json — mafia
    Mafia: 'Mafia',
    'Each night, choose a target with your family.':
      'Cada noche, elige un objetivo con tu familia.',
    'The mafia!': '¡La mafia!',
    Detective: 'Detective',
    Detectives: 'Detectives',
    'Each night, investigate one player: mafia or not.':
      'Cada noche, investiga a alguien: ¿mafia o no?',
    'The detective.': 'El detective.',
    'Each night, protect one player from the mafia.': 'Cada noche, protege a alguien de la mafia.',
    Townsperson: 'Vecino',
    Townspeople: 'Vecinos',
    'Find the mafia and vote them out.': 'Encuentra a la mafia y expúlsala.',
    'A townsperson.': 'Un vecino.',
    Vigilante: 'Justiciero',
    Vigilantes: 'Justicieros',
    'The vigilante.': 'El justiciero.',
    'Get the town to vote you out, and you win.': 'Si la ciudad te expulsa, ganas tú.',
    'The mafia': 'La mafia',
    'The town': 'La ciudad',
    'in the mafia': 'de la mafia',
    'the mafia': 'la mafia',
    detective: 'detective',
    townsperson: 'vecino',
    "Who's in the mafia?": '¿Quién es de la mafia?',
    'Your family': 'Tu familia',
    'Family picks': 'Elecciones de la familia',
    '{name} is MAFIA': '{name} es de la MAFIA',
    '{name} is not mafia': '{name} no es de la mafia',
    'The family chose {name}': 'La familia eligió a {name}',
    "Choose tonight's target": 'Elige el objetivo de esta noche',
    "That's your family!": '¡Es de tu familia!',
    'The town sleeps.': 'La ciudad duerme.',
    "Discuss. Who's in the mafia?": 'A discutir. ¿Quién es de la mafia?',
    "Ghosts, stay silent. Discuss. Who's in the mafia?":
      'Fantasmas, silencio. A discutir. ¿Quién es de la mafia?',
    "The town couldn't agree.": 'La ciudad no se puso de acuerdo.',
    'The vigilante takes aim…': 'El justiciero apunta…',
    'The mafia wins.': 'Gana la mafia.',
    'The town wins!': '¡Gana la ciudad!',
    '{name} packed up and left town.': '{name} hizo las maletas y se fue de la ciudad.',
    'The vigilante took {name} down.': 'El justiciero se llevó a {name}.',

    // server-written: night jobs and reports, awards
    'Choose someone to check': 'Elige a alguien para investigar',
    'Choose someone to protect': 'Elige a alguien para proteger',
    'Who do you suspect?': '¿De quién sospechas?',
    'You protected {name}': 'Protegiste a {name}',
    'Your hunch: {name}': 'Tu corazonada: {name}',
    'Nobody was chosen last night': 'Anoche no se eligió a nadie',
    "You didn't choose anyone last night": 'Anoche no elegiste a nadie',
    '🔮 Sharp Eyes': '🔮 Ojo de lince',
    'Unmasked a hidden foe': 'Desenmascaró a un enemigo oculto',
    'Unmasked {n} hidden foes': 'Desenmascaró a {n} enemigos ocultos',
    '🩺 Life Saver': '🩺 Salvavidas',
    'Saved someone from the night': 'Salvó a alguien de la noche',
    'Saved {n} people from the night': 'Salvó a {n} personas de la noche',
    '🗳️ Wolf Hunter': '🗳️ Cazalobos',
    '{n} day votes on the right target': '{n} votos de día al blanco correcto',
    '🎭 Best Liar': '🎭 Mejor mentiroso',
    'Drew just {n} vote in daylight': 'Recibió solo {n} voto a la luz del día',
    'Drew just {n} votes in daylight': 'Recibió solo {n} votos a la luz del día',
    '👻 First to Fall': '👻 Primero en caer',
    'Gone first, never forgotten': 'Se fue primero, nunca olvidado',

    ...STRINGS_UI_ES,
  },
};
