// The Spanish for Nightfall's own screens (TV and phone), keyed by the English sentence. Split from
// strings.ts so each file stays readable; strings.ts spreads this table into STRINGS.es.
export const STRINGS_UI_ES: Record<string, string> = {
  // phone — shared
  '🤔 = the night’s hunches: who the villagers suspect (anonymous).':
    '🤔 = las corazonadas de la noche: de quién sospechan los aldeanos (anónimo).',
  '{ready} of {total} have seen their role': '{ready} de {total} ya vieron su rol',
  'Tap to see your role': 'Toca para ver tu rol',
  'Tap to see your night job': 'Toca para ver tu tarea de la noche',
  'Tap to see your night report': 'Toca para ver tu informe de la noche',
  'Tap to see every role': 'Toca para ver todos los roles',
  'It hides again by itself.': 'Se vuelve a ocultar sola.',
  'Keep it close: neighbours peek.': 'Tápala bien: los vecinos miran.',
  "You're in as soon as this one ends": 'Entras en cuanto termine esta',
  'Hold to see your role': 'Mantén pulsado para ver tu rol',
  'One moment…': 'Un momento…',
  'Watch the TV': 'Mira la TV',
  "You're a ghost.": 'Eres un fantasma.',
  'Watch, but stay silent.': 'Mira, pero en silencio.',
  'Hold to see your night report': 'Mantén pulsado para ver tu informe de la noche',
  'Hold to see every role': 'Mantén pulsado para ver todos los roles',
  'The village': 'El pueblo',
  // phone — roles and night
  'Waiting for the others': 'Esperando a los demás',
  'Got it': 'Entendido',
  'Your secret role': 'Tu rol secreto',
  'Keep it secret. Hold the card close.': 'Guárdalo en secreto. Tapa bien la tarjeta.',
  'Pick someone else.': 'Elige a otra persona.',
  'You protected them last night.': 'Anoche ya protegiste a esa persona.',
  'Night {n}': 'Noche {n}',
  'Choose someone': 'Elige a alguien',
  'Hold to see your night job': 'Mantén pulsado para ver tu tarea de la noche',
  You: 'Tú',
  'Chosen: {name} · tap another to change': 'Elegido: {name} · toca a otro para cambiar',
  'Tap a face. Nobody can see what it means.': 'Toca una cara. Nadie sabe qué significa.',
  // phone — day
  "That's your 3 posts for today": 'Ya usaste tus 3 mensajes de hoy',
  'Write something first.': 'Escribe algo primero.',
  'Post to the town board': 'Publicar en el tablón del pueblo',
  'Post… ({left} left)': 'Publica… ({left})',
  'No posts left today': 'Hoy ya no te quedan mensajes',
  Post: 'Publicar',
  '{ready} of {living} ready to vote': '{ready} de {living} listos para votar',
  'Ready · tap to undo': 'Listo · toca para deshacer',
  'Ready to vote ✋': 'Listo para votar ✋',
  'Discuss! {question}': '¡A discutir! {question}',
  'Nobody has posted yet.': 'Nadie ha publicado todavía.',
  // phone — vote, hunter, last words
  'No one': 'Nadie',
  'Pick someone to vote out': 'Elige a quién expulsar',
  'Change my vote to {name}': 'Cambiar mi voto a {name}',
  'Vote: {name}': 'Votar: {name}',
  'Voted: {name}': 'Votaste: {name}',
  'Runoff: vote again': 'Desempate: vota otra vez',
  'Who goes? Vote.': '¿Quién se va? Vota.',
  'Your vote stays secret until the verdict.': 'Tu voto es secreto hasta el veredicto.',
  '🏹 Take {name} down': '🏹 Llevarte a {name}',
  "You're taking someone with you. Choose.": 'Te llevas a alguien contigo. Elige.',
  '{name}’s last words…': 'Las últimas palabras de {name}…',
  'Say it': 'Decirlo',
  'Your last words': 'Tus últimas palabras',
  'One line for the TV. Make it count.': 'Una frase para la TV. Que valga la pena.',
  'Say something…': 'Di algo…',
  // phone — dawn, verdict, end
  "You didn't survive the night.": 'No sobreviviste a la noche.',
  'Your role: {role}': 'Tu rol: {role}',
  'You survived the night.': 'Sobreviviste a la noche.',
  'The village wakes…': 'El pueblo despierta…',
  'You were voted out.': 'Te expulsaron.',
  'You were: {role}': 'Eras: {role}',
  'You won!': '¡Ganaste!',
  'Not this time.': 'Esta vez no.',
  // TV
  'The roles in this game': 'Los roles de esta partida',
  'Check your role. Keep it secret.': 'Mira tu rol. Guárdalo en secreto.',
  'Everyone, look at your phone and keep it close.': 'Todos, miren su teléfono y tápenlo bien.',
  '{done} of {total} have chosen': '{done} de {total} ya eligieron',
  'Day {n}': 'Día {n}',
  'Posts from the phones appear here.': 'Aquí aparecen los mensajes de los teléfonos.',
  'Tie! {names}?': '¡Empate! ¿{names}?',
  ' or ': ' o ',
  'Vote now': 'A votar',
  'Vote again: only the tied players, or No one.': 'Voten otra vez: solo los empatados, o Nadie.',
  'Vote on your phone.': 'Vota en tu teléfono.',
  '{done} of {total} have voted': '{done} de {total} ya votaron',
  'The graveyard': 'El cementerio',
  'The hunter is choosing on their phone.': 'El cazador está eligiendo en su teléfono.',
  "It's a tie": 'Hay empate',
  'No one had the most votes': 'Nadie tuvo más votos',
  'The jester got themselves voted out.': 'El bufón consiguió que lo expulsaran.',
  'Every member of the mafia was found.': 'Descubrieron a todos los de la mafia.',
  'Every wolf was found.': 'Descubrieron a todos los lobos.',
  'The mafia equals the rest of the town.': 'La mafia iguala al resto de la ciudad.',
  'The wolves equal the rest.': 'Los lobos igualan al resto.',
  'The mafia survived the last day.': 'La mafia sobrevivió al último día.',
  'The wolves survived the last day.': 'Los lobos sobrevivieron al último día.',
  saved: 'salvado',
  quiet: 'tranquila',
  'no one': 'nadie',
};
