// Tune In's TV and shared sentences in Spanish, keyed by the English (ADR-044; see strings.ts).
// "Psychic" is "vidente"; the teams are "Sol" and "Luna"; the call stays IZQUIERDA / DERECHA.
export const STRINGS_TV: Record<string, string> = {
  '📻 Tune In': '📻 Sintoniza',
  'Solo · everyone for themselves': 'Solo · cada quien por su cuenta',
  'Teams · ▲ Sun against ● Moon': 'Equipos · ▲ Sol contra ● Luna',
  'Co-op · the whole room against the dial': 'Cooperativo · toda la sala contra el dial',
  '▲ Sun': '▲ Sol',
  '● Moon': '● Luna',
  Sun: 'Sol',
  Moon: 'Luna',
  'Round {n} of {total}': 'Ronda {n} de {total}',
  'Turn {n} · {team}': 'Turno {n} · {team}',
  '{name} is the psychic': '{name} es el vidente',
  '{name} is thinking': '{name} está pensando',
  'Tuning in': 'Sintonizando',
  'Group {total} / {max}': 'Grupo {total} / {max}',
  'CATCH-UP!': '¡REMONTADA!',
  'First to {n}': 'Primero a {n}',
  '📺 No signal!': '📺 ¡Sin señal!',
  'No clue came through. Nobody scores.': 'No llegó ninguna pista. Nadie puntúa.',
  '{team}: is the target LEFT or RIGHT of the needle?':
    '{team}: ¿el objetivo está a la IZQUIERDA o a la DERECHA de la aguja?',
  '{team} called {side}': '{team} dijo {side}',
  LEFT: 'IZQUIERDA',
  RIGHT: 'DERECHA',
  '✓ +1': '✓ +1',
  '✗': '✗',
  'Bullseye!': '¡En el blanco!',
  'Close!': '¡Cerca!',
  'Missed it.': 'Fallado.',
  'Perfect tune!': '¡Sintonía perfecta!',
  '🧠 Mind meld!': '🧠 ¡Conexión mental!',
  '📡 Crystal clear!': '📡 ¡Clarísimo!',
  '📻 Tuning in.': '📻 Sintonizando.',
  '📺 Static.': '📺 Estática.',
  'Final scores': 'Puntuación final',
  'Final score': 'Resultado final',
  'After round {n}': 'Tras la ronda {n}',
  'After turn {n}': 'Tras el turno {n}',
  'Winners!': '¡Ganadores!',
  '★ {name} taps Next round when everyone’s ready':
    '★ {name} toca Siguiente ronda cuando todos estén listos',
  '★ {name} taps See results': '★ {name} toca Ver resultados',
  'first up': 'empieza',
  '{team} plays first · {name} reads the first dial': '{team} empieza · {name} lee el primer dial',
  'No clue this round': 'Sin pista esta ronda',
  'Waiting for {name} to reconnect': 'Esperando a que {name} vuelva',
  '{names} & {last}': '{names} y {last}',
  '{team} hit the bullseye and goes again!': '¡{team} dio en el blanco y vuelve a jugar!',
  'Next up: {team}': 'Ahora juega {team}',
  '+{n} for the group this round': '+{n} para el grupo en esta ronda',
};
