// Tune In's phone sentences in Spanish, keyed by the English (ADR-044; see strings.ts).
export const STRINGS_PHONE: Record<string, string> = {
  "You're the psychic 📻": 'Eres el vidente 📻',
  'Hold to see the target': 'Mantén pulsado para ver el objetivo',
  'Your clue…': 'Tu pista…',
  'Your clue': 'Tu pista',
  'Your clue:': 'Tu pista:',
  '✓ Good to go': '✓ Lista para enviar',
  "Name something that sits right on the target. No numbers, no 'left' or 'right'.":
    "Nombra algo que caiga justo en el objetivo. Sin números, ni 'izquierda' ni 'derecha'.",
  'Send clue': 'Enviar pista',
  Sent: 'Enviada',
  'Type a clue.': 'Escribe una pista.',
  'Keep it under 30 characters.': 'Que tenga menos de 30 caracteres.',
  'No numbers. Describe it instead.': 'Sin números. Descríbelo.',
  "Don't use the dial's own words.": 'No uses las palabras del dial.',
  'Describe a thing, not a spot on the dial.': 'Describe algo, no un punto del dial.',
  'Psychics stay silent! 🤫': '¡Los videntes no hablan! 🤫',
  "{name}'s clue": 'Pista de {name}',
  'Lock in': 'Fijar',
  'Locked in': 'Fijado',
  'Move left': 'Mover a la izquierda',
  'Move right': 'Mover a la derecha',
  'Your dial': 'Tu dial',
  'Slide to where the clue lands': 'Desliza hasta donde cae la pista',
  'Your team sees your dial move. Talk it out, then lock in.':
    'Tu equipo ve moverse tu dial. Háblenlo y luego fija.',
  'Nobody sees your dial until the reveal.': 'Nadie ve tu dial hasta la revelación.',
  '◀ LEFT': '◀ IZQUIERDA',
  'RIGHT ▶': 'DERECHA ▶',
  'toward {end}': 'hacia {end}',
  'Clue: “{clue}”': 'Pista: «{clue}»',
  '{team} set their needle. Is the target LEFT or RIGHT of it?':
    '{team} colocó su aguja. ¿El objetivo está a la IZQUIERDA o a la DERECHA?',
  '{name} is thinking of a clue…': '{name} está pensando una pista…',
  'Where would it land? Get ready to slide.': '¿Dónde caería? Prepárate para deslizar.',
  'The other team is calling LEFT or RIGHT…': 'El otro equipo está diciendo IZQUIERDA o DERECHA…',
  '{team} is tuning in…': '{team} está sintonizando…',
  'Next, your team calls LEFT or RIGHT of their needle.':
    'Después, tu equipo dice IZQUIERDA o DERECHA de su aguja.',
  "You're in as soon as this one ends": 'Entras en cuanto termine esta partida',
  "You're on {team}": 'Estás en {team}',
  'Thanks for playing!': '¡Gracias por jugar!',
  'Here it comes…': 'Ahí viene…',
  '👀 Watch the TV': '👀 Mira la TV',
  'The target is opening up.': 'El objetivo se está abriendo.',
  'No signal — nobody scores this round.': 'Sin señal: nadie puntúa en esta ronda.',
  'Nobody dialled — 0 this time.': 'Nadie movió el dial: 0 esta vez.',
  'Your guessers averaged {avg} → +{pts}': 'Tus adivinos promediaron {avg} → +{pts}',
  'The group needle scored +{pts}': 'La aguja del grupo sumó +{pts}',
  "Your team's needle scored +{pts}": 'La aguja de tu equipo sumó +{pts}',
  'The group needle missed': 'La aguja del grupo no acertó',
  "Your team's needle missed": 'La aguja de tu equipo no acertó',
  'You were {n} away': 'Quedaste a {n}',
  'No call this time.': 'Esta vez no hubo llamada.',
  'Your team called {side} — right!': 'Tu equipo dijo {side}: ¡acierto!',
  'Your team called {side} — not this time.': 'Tu equipo dijo {side}: esta vez no.',
  "You didn't dial this time.": 'Esta vez no moviste el dial.',
  '{team}: {n} of {goal}': '{team}: {n} de {goal}',
  'Waiting for {name} to reconnect…': 'Esperando a que {name} vuelva…',
  'I’m ready': 'Estoy listo',
  'Ready!': '¡Listo!',
  'Read the rules, then tap I’m ready': 'Lee las reglas y toca Estoy listo',
  'Waiting for the others · {n} of {total} ready': 'Esperando a los demás · {n} de {total} listos',
  'Your total: {n} · place {place} of {count}': 'Tu total: {n} · puesto {place} de {count}',
  '{n} of {total} locked in': '{n} de {total} fijaron',
  '{n} of {total} called': '{n} de {total} eligieron',
};
